// ==========================================
// 漢字拆字大師 - Part 1 完整代碼（第1 - 100關）
// 難度梯度：入門（難度1）到基礎（難度2），去除了“一二三”等死板重復答案
// ==========================================

const levelData = [
    // ========== 難度1：入門階段（1-40關：獨體字與極簡結構，找出2-4個隱藏字） ==========
    { id: 1, character: '大', hiddenWords: ['人', '大'], distractors: ['天', '太', '犬', '木', '个'], difficulty: 1 },
    { id: 2, character: '天', hiddenWords: ['大', '人', '天'], distractors: ['夫', '太', '夭', '开', '无'], difficulty: 1 },
    { id: 3, character: '太', hiddenWords: ['大', '人', '太'], distractors: ['天', '犬', '木', '本', '头'], difficulty: 1 },
    { id: 4, character: '犬', hiddenWords: ['大', '人', '犬'], distractors: ['太', '天', '伏', '尤', '拔'], difficulty: 1 },
    { id: 5, character: '木', hiddenWords: ['木', '人'], distractors: ['本', '未', '末', '术', '禾'], difficulty: 1 },
    { id: 6, character: '本', hiddenWords: ['木', '人', '本'], distractors: ['未', '末', '术', '体', '笨'], difficulty: 1 },
    { id: 7, character: '未', hiddenWords: ['木', '人', '未'], distractors: ['末', '本', '朱', '味', '妹'], difficulty: 1 },
    { id: 8, character: '末', hiddenWords: ['木', '人', '末'], distractors: ['未', '本', '抹', '沫', '茉'], difficulty: 1 },
    { id: 9, character: '禾', hiddenWords: ['木', '人', '禾'], distractors: ['千', '千', '和', '秋', '秀'], difficulty: 1 },
    { id: 10, character: '米', hiddenWords: ['木', '人', '米'], distractors: ['来', '迷', '眯', '粉', '粒'], difficulty: 1 },
    { id: 11, character: '人', hiddenWords: ['人'], distractors: ['个', '从', '众', '大', '天', '入', '八'], difficulty: 1 },
    { id: 12, character: '从', hiddenWords: ['人', '从'], distractors: ['众', '丛', '队', '闪', '人'], difficulty: 1 },
    { id: 13, character: '众', hiddenWords: ['人', '从', '众'], distractors: ['丛', '聚', '大', '天', '太'], difficulty: 1 },
    { id: 14, character: '火', hiddenWords: ['人', '火'], distractors: ['灭', '灯', '灰', '大', '太'], difficulty: 1 },
    { id: 15, character: '灭', hiddenWords: ['火', '人', '灭'], distractors: ['大', '天', '灰', '灾', '灵'], difficulty: 1 },
    { id: 16, character: '灰', hiddenWords: ['火', '人', '灰'], distractors: ['灭', '炭', '恢', '大', '友'], difficulty: 1 },
    { id: 17, character: '闪', hiddenWords: ['门', '人', '闪'], distractors: ['问', '间', '闷', '闭', '闯'], difficulty: 1 },
    { id: 18, character: '闭', hiddenWords: ['门', '才', '闭'], distractors: ['闪', '问', '间', '闷', '闲'], difficulty: 1 },
    { id: 19, character: '问', hiddenWords: ['门', '口', '问'], distractors: ['闪', '间', '闷', '闻', '闯'], difficulty: 1 },
    { id: 20, character: '间', hiddenWords: ['门', '日', '口', '间'], distractors: ['问', '闪', '闷', '简', '润'], difficulty: 1 },
    { id: 21, character: '闷', hiddenWords: ['门', '心', '闷'], distractors: ['闪', '问', '间', '闭', '闹'], difficulty: 1 },
    { id: 22, character: '闯', hiddenWords: ['门', '马', '闯'], distractors: ['闪', '问', '间', '闭', '闲'], difficulty: 1 },
    { id: 23, character: '牛', hiddenWords: ['牛'], distractors: ['午', '告', '先', '牢', '牧', '件'], difficulty: 1 },
    { id: 24, character: '牢', hiddenWords: ['牛', '牢'], distractors: ['穴', '空', '牵', '件', '犁'], difficulty: 1 },
    { id: 25, character: '牧', hiddenWords: ['牛', '牧'], distractors: ['放', '收', '攻', '特', '物'], difficulty: 1 },
    { id: 26, character: '物', hiddenWords: ['牛', '勿', '物'], distractors: ['匆', '易', '吻', '特', '牲'], difficulty: 1 },
    { id: 27, character: '特', hiddenWords: ['牛', '寺', '寸', '特'], distractors: ['持', '等', '待', '侍', '詩'], difficulty: 1 },
    { id: 28, character: '王', hiddenWords: ['王'], distractors: ['玉', '主', '弄', '皇', '旺', '全'], difficulty: 1 },
    { id: 29, character: '玉', hiddenWords: ['王', '玉'], distractors: ['主', '国', '宝', '莹', '璧'], difficulty: 1 },
    { id: 30, character: '主', hiddenWords: ['王', '主'], distractors: ['玉', '注', '住', '柱', '往'], difficulty: 1 },
    { id: 31, character: '弄', hiddenWords: ['王', '开', '弄'], distractors: ['异', '弃', '葬', '弊', '算'], difficulty: 1 },
    { id: 32, character: '皇', hiddenWords: ['白', '口', '王', '皇'], distractors: ['煌', '凰', '泉', '腺', '魄'], difficulty: 1 },
    { id: 33, character: '全', hiddenWords: ['人', '大', '王', '全'], distractors: ['金', '企', '令', '合', '仓'], difficulty: 1 },
    { id: 34, character: '口', hiddenWords: ['口'], distractors: ['日', '田', '目', '白', '石', '右'], difficulty: 1 },
    { id: 35, character: '古', hiddenWords: ['十', '口', '古'], distractors: ['舌', '克', '估', '故', '胡'], difficulty: 1 },
    { id: 36, character: '右', hiddenWords: ['口', '右'], distractors: ['左', '石', '若', '占', '佑'], difficulty: 1 },
    { id: 37, character: '占', hiddenWords: ['卜', '口', '占'], distractors: ['点', '沾', '站', '战', '钻'], difficulty: 1 },
    { id: 38, character: '召', hiddenWords: ['刀', '口', '召'], distractors: ['招', '沼', '超', '紹', '迢'], difficulty: 1 },
    { id: 39, character: '只', hiddenWords: ['口', '八', '只'], distractors: ['识', '炽', '织', '职', '积'], difficulty: 1 },
    { id: 40, character: '兄', hiddenWords: ['口', '儿', '兄'], distractors: ['兑', '克', '兢', '況', '祝'], difficulty: 1 },

    // ========== 難度2：基礎階段（41-80關：標準左右/上下結構，拆解出2-4個清晰字） ==========
    { id: 41, character: '休', hiddenWords: ['人', '木', '休'], distractors: ['体', '沐', '保', '仆', '估', '伴'], difficulty: 2 },
    { id: 42, character: '体', hiddenWords: ['人', '本', '木', '体'], distractors: ['休', '笨', '体', '估', '仗', '佃'], difficulty: 2 },
    { id: 43, character: '位', hiddenWords: ['人', '立', '位'], distractors: ['拉', '泣', '粒', '垃', '陪', '焙'], difficulty: 2 },
    { id: 44, character: '估', hiddenWords: ['人', '古', '十', '口', '估'], distractors: ['枯', '姑', '故', '胡', '做', '佑'], difficulty: 2 },
    { id: 45, character: '伙', hiddenWords: ['人', '火', '伙'], distractors: ['秋', '伴', '队', '闪', '燃', '煬'], difficulty: 2 },
    { id: 46, character: '何', hiddenWords: ['人', '可', '口', '何'], distractors: ['河', '苛', '荷', '呵', '奇', '倚'], difficulty: 2 },
    { id: 47, character: '但', hiddenWords: ['人', '旦', '日', '口', '但'], distractors: ['担', '坦', '胆', '袒', '查', '理'], difficulty: 2 },
    { id: 48, character: '伯', hiddenWords: ['人', '白', '口', '伯'], distractors: ['怕', '拍', '迫', '舶', '柏', '泉'], difficulty: 2 },
    { id: 49, character: '仲', hiddenWords: ['人', '中', '口', '仲'], distractors: ['冲', '种', '钟', '肿', '串', '伸'], difficulty: 2 },
    { id: 50, character: '伸', hiddenWords: ['人', '申', '田', '口', '伸'], distractors: ['神', '绅', '审', '砷', '呻', '坤'], difficulty: 2 },
    { id: 51, character: '尖', hiddenWords: ['小', '大', '人', '尖'], distractors: ['尘', '卡', '少', '劣', '光', '省'], difficulty: 2 },
    { id: 52, character: '尘', hiddenWords: ['小', '土', '尘'], distractors: ['尖', '堂', '坐', '聖', '壁', '墨'], difficulty: 2 },
    { id: 53, character: '卡', hiddenWords: ['上', '下', '卡'], distractors: ['尖', '卡', '占', '卢', '卞', '乒'], difficulty: 2 },
    { id: 54, character: '引', hiddenWords: ['弓', '引'], distractors: ['张', '弥', '弦', '弹', '强', '弘'], difficulty: 2 },
    { id: 55, character: '北', hiddenWords: ['匕', '北'], distractors: ['此', '些', '背', '兆', '非', '比'], difficulty: 2 },
    { id: 56, character: '明', hiddenWords: ['日', '月', '口', '明'], distractors: ['朋', '晶', '晃', '昆', '昌', '盟'], difficulty: 2 },
    { id: 57, character: '朋', hiddenWords: ['月', '朋'], distractors: ['明', '棚', '蹦', '崩', '绷', '塑'], difficulty: 2 },
    { id: 58, character: '岩', hiddenWords: ['山', '石', '口', '岩'], distractors: ['岸', '炭', '宕', '矿', '研', '碧'], difficulty: 2 },
    { id: 59, character: '島', hiddenWords: ['山', '鸟', '岛'], distractors: ['乌', '鸣', '捣', '鸭', '鸠', '鸾'], difficulty: 2 },
    { id: 60, character: '泉', hiddenWords: ['白', '水', '口', '泉'], distractors: ['腺', '原', '愿', '線', '漂', '淼'], difficulty: 2 },
    { id: 61, character: '林', hiddenWords: ['木', '人', '林'], distractors: ['森', '淋', '麻', '楚', '焚', '禁'], difficulty: 2 },
    { id: 62, character: '森', hiddenWords: ['木', '人', '林', '森'], distractors: ['淋', '淼', '焱', '磊', '焱', '蓬'], difficulty: 2 },
    { id: 63, character: '相', hiddenWords: ['木', '目', '人', '口', '相'], distractors: ['想', '箱', '霜', '湘', '廂', '柏'], difficulty: 2 },
    { id: 64, character: '杳', hiddenWords: ['木', '日', '人', '口', '杳'], distractors: ['查', '杏', '香', '杳', '李', '杰'], difficulty: 2 },
    { id: 65, character: '析', hiddenWords: ['木', '斤', '人', '析'], distractors: ['折', '听', '近', '匠', '欣', '斯'], difficulty: 2 },
    { id: 66, character: '村', hiddenWords: ['木', '寸', '人', '村'], distractors: ['衬', '付', '守', '討', '耐', '尋'], difficulty: 2 },
    { id: 67, character: '板', hiddenWords: ['木', '反', '人', '板'], distractors: ['饭', '返', '版', '贩', '叛', '阪'], difficulty: 2 },
    { id: 68, character: '枉', hiddenWords: ['木', '王', '人', '枉'], distractors: ['狂', '旺', '汪', '匡', '拄', '班'], difficulty: 2 },
    { id: 69, character: '松', hiddenWords: ['木', '公', '八', '人', '松'], distractors: ['讼', '颂', '翁', '蚣', '瓮', '菘'], difficulty: 2 },
    { id: 70, character: '柱', hiddenWords: ['木', '主', '王', '人', '柱'], distractors: ['注', '住', '拄', '駐', '往', '弦'], difficulty: 2 },
    { id: 71, character: '拿', hiddenWords: ['合', '手', '人', '口', '拿'], distractors: ['掌', '挚', '攀', '擎', '摹', '掰'], difficulty: 2 },
    { id: 72, character: '掰', hiddenWords: ['手', '分', '八', '刀', '掰'], distractors: ['掰', '排', '拜', '攀', '摩', '掰'], difficulty: 2 },
    { id: 73, character: '看', hiddenWords: ['手', '目', '口', '看'], distractors: ['着', '眷', '羞', '眉', '盾', '省'], difficulty: 2 },
    { id: 74, character: '盲', hiddenWords: ['亡', '目', '口', '盲'], distractors: ['荒', '忙', '茫', '妄', '忘', '望'], difficulty: 2 },
    { id: 75, character: '盯', hiddenWords: ['目', '丁', '口', '盯'], distractors: ['钉', '顶', '叮', '订', '厅', '宁'], difficulty: 2 },
    { id: 76, character: '泪', hiddenWords: ['水', '目', '口', '泪'], distractors: ['湘', '汨', '渺', '沫', '浪', '泪'], difficulty: 2 },
    { id: 77, character: '盼', hiddenWords: ['目', '分', '八', '刀', '口', '盼'], distractors: ['扮', '份', '粉', '盆', '吩', '芬'], difficulty: 2 },
    { id: 78, character: '眉', hiddenWords: ['目', '口', '眉'], distractors: ['媚', '楣', '嵋', '看', '省', '眷'], difficulty: 2 },
    { id: 79, character: '眯', hiddenWords: ['目', '米', '木', '人', '口', '眯'], distractors: ['迷', '謎', '醚', '咪', '咪', '咪'], difficulty: 2 },
    { id: 80, character: '瞇', hiddenWords: ['目', '米', '木', '人', '口', '瞇'], distractors: ['眯', '迷', '謎', '瞇', '瞇', '瞇'], difficulty: 2 },

// ========== 難度2進階：複合字形（81-100關：包圍結構、復雜重疊，需要更細心） ==========
    { id: 81, character: '杏', hiddenWords: ['木', '口', '人', '杏'], distractors: ['呆', '查', '杳', '束', '困', '固'], difficulty: 2 },
    { id: 82, character: '呆', hiddenWords: ['口', '木', '人', '呆'], distractors: ['杏', '保', '集', '架', '榮', '某'], difficulty: 2 },
    { id: 83, character: '囚', hiddenWords: ['口', '人', '囚'], distractors: ['因', '国', '四', '回', '团', '圈'], difficulty: 2 },
    { id: 84, character: '因', hiddenWords: ['口', '大', '人', '因'], distractors: ['囚', '困', '团', '园', '固', '恩'], difficulty: 2 },
    { id: 85, character: '困', hiddenWords: ['口', '木', '人', '困'], distractors: ['因', '固', '圈', '囫', '囵', '圃'], difficulty: 2 },
    { id: 86, character: '固', hiddenWords: ['口', '古', '十', '固'], distractors: ['困', '因', '锢', '箇', '個', '涸'], difficulty: 2 },
    { id: 87, character: '国', hiddenWords: ['口', '王', '玉', '国'], distractors: ['园', '围', '图', '固', '圈', '圃'], difficulty: 2 },
    { id: 88, character: '图', hiddenWords: ['口', '冬', '图'], distractors: ['国', '园', '围', '圈', '圉', '圄'], difficulty: 2 },
    { id: 89, character: '东', hiddenWords: ['木', '人', '东'], distractors: ['乐', '栋', '陈', '冻', '练', '柬'], difficulty: 2 },
    { id: 90, character: '卡', hiddenWords: ['上', '下', '卡'], distractors: ['占', '步', '卢', '卓', '乒', '乓'], difficulty: 2 },
    { id: 91, character: '古', hiddenWords: ['十', '口', '古'], distractors: ['舌', '故', '枯', '居', '苦', '克'], difficulty: 2 },
    { id: 92, character: '克', hiddenWords: ['十', '口', '儿', '克'], distractors: ['兄', '兢', '克服', '充', '兑', '吊'], difficulty: 2 },
    { id: 93, character: '合', hiddenWords: ['人', '口', '合'], distractors: ['盒', '哈', '答', '拾', '塔', '给'], difficulty: 2 },
    { id: 94, character: '吉', hiddenWords: ['士', '口', '吉'], distractors: ['志', '洁', '结', '桔', '喆', '古'], difficulty: 2 },
    { id: 95, character: '吞', hiddenWords: ['天', '大', '人', '口', '吞'], distractors: ['蚕', '歪', '否', '杏', '呆', '吾'], difficulty: 2 },
    { id: 96, character: '吾', hiddenWords: ['五', '口', '吾'], distractors: ['语', '梧', '衙', '悟', '吞', '杏'], difficulty: 2 },
    { id: 97, character: '含', hiddenWords: ['今', '人', '口', '含'], distractors: ['念', '贪', '吟', '晗', '颔', '怜'], difficulty: 2 },
    { id: 98, character: '谷', hiddenWords: ['八', '人', '口', '谷'], distractors: ['欲', '俗', '浴', '容', '裕', '卻'], difficulty: 2 },
    { id: 99, character: '杏', hiddenWords: ['木', '口', '人', '杏'], distractors: ['呆', '束', '枯', '研', '否', '各'], difficulty: 2 },
    { id: 100, character: '吳', hiddenWords: ['口', '大', '人', '吳'], distractors: ['娱', '误', '蜈', '噢', '悞', '噭'], difficulty: 2 },

    // ========== 難度2-3：中等階梯（101-160關：常見形聲與會意字，漢字結構更豐富） ==========
    { id: 101, character: '李', hiddenWords: ['木', '子', '人', '了', '李'], distractors: ['季', '杏', '柔', '婪', '孟', '仔'], difficulty: 2 },
    { id: 102, character: '季', hiddenWords: ['禾', '木', '人', '子', '了', '季'], distractors: ['李', '委', '秀', '透', '俘', '孝'], difficulty: 2 },
    { id: 103, character: '委', hiddenWords: ['禾', '女', '木', '人', '委'], distractors: ['季', '姜', '姿', '要', '魏', '矮'], difficulty: 2 },
    { id: 104, character: '姜', hiddenWords: ['羊', '女', '姜'], distractors: ['美', '羔', '羞', '姿', '妥', '娄'], difficulty: 2 },
    { id: 105, character: '姿', hiddenWords: ['次', '女', '欠', '姿'], distractors: ['资', '恣', '咨', '瓷', '羨', '盜'], difficulty: 2 },
    { id: 106, character: '絮', hiddenWords: ['如', '女', '口', '糸', '絮'], distractors: ['紧', '紫', '索', '累', '恕', '恕'], difficulty: 3 },
    { id: 107, character: '恕', hiddenWords: ['如', '女', '口', '心', '恕'], distractors: ['怒', '怨', '恕', '恐', '恋', '恕'], difficulty: 3 },
    { id: 108, character: '怨', hiddenWords: ['夕', '心', '怨'], distractors: ['怒', '恕', '恐', '悲', '急', '忽'], difficulty: 3 },
    { id: 109, character: '祭', hiddenWords: ['夕', '示', '祭'], distractors: ['察', '擦', '蔡', '際', '瘵', '穄'], difficulty: 3 },
    { id: 110, character: '禁', hiddenWords: ['林', '木', '人', '示', '禁'], distractors: ['楚', '焚', '婪', '襟', '噤', '澿'], difficulty: 3 },
    { id: 111, character: '焚', hiddenWords: ['林', '木', '人', '火', '焚'], distractors: ['禁', '楚', '婪', '梵', '婪', '婪'], difficulty: 3 },
    { id: 112, character: '楚', hiddenWords: ['林', '木', '人', '疋', '楚'], distractors: ['禁', '焚', '婪', '礎', '模糊', '楚'], difficulty: 3 },
    { id: 113, character: '霖', hiddenWords: ['雨', '林', '木', '人', '霖'], distractors: ['霜', '雹', '露', '霸', '震', '霉'], difficulty: 3 },
    { id: 114, character: '露', hiddenWords: ['雨', '路', '足', '各', '口', '露'], distractors: ['霜', '雹', '霸', '霧', '靂', '霾'], difficulty: 3 },
    { id: 115, character: '霜', hiddenWords: ['雨', '木', '目', '口', '相', '霜'], distractors: ['雪', '霞', '雹', '霧', '霸', '靂'], difficulty: 3 },
    { id: 116, character: '霞', hiddenWords: ['雨', '叚', '二', '霞'], distractors: ['霜', '雹', '霸', '霧', '靂', '霾'], difficulty: 3 },
    { id: 117, character: '霸', hiddenWords: ['雨', '革', '月', '霸'], distractors: ['霜', '雹', '露', '霧', '靂', '霾'], difficulty: 3 },
    { id: 118, character: '霆', hiddenWords: ['雨', '廷', '壬', '霆'], distractors: ['雷', '震', '霉', '霍', '霓', '霎'], difficulty: 3 },
    { id: 119, character: '震', hiddenWords: ['雨', '辰', '震'], distractors: ['雷', '霆', '霉', '霍', '霓', '霎'], difficulty: 3 },
    { id: 120, character: '霉', hiddenWords: ['雨', '每', '人', '母', '霉'], distractors: ['雷', '震', '霆', '霍', '霓', '霎'], difficulty: 3 },
    { id: 121, character: '智', hiddenWords: ['知', '矢', '口', '日', '智'], distractors: ['蜘', '痴', '踟', '矩', '短', '矮'], difficulty: 3 },
    { id: 122, character: '蠢', hiddenWords: ['春', '日', '人', '虫', '蠢'], distractors: ['香', '秦', '泰', '奏', '蠢', '蠢'], difficulty: 3 },
    { id: 123, character: '香', hiddenWords: ['禾', '木', '人', '日', '口', '香'], distractors: ['季', '秀', '委', '禿', '乘', '剩'], difficulty: 2 },
    { id: 124, character: '禿', hiddenWords: ['禾', '木', '人', '几', '禿'], distractors: ['秀', '香', '季', '委', '乘', '禿'], difficulty: 2 },
    { id: 125, character: '秀', hiddenWords: ['禾', '木', '人', '乃', '秀'], distractors: ['禿', '香', '季', '委', '透', '誘'], difficulty: 2 },
    { id: 126, character: '透', hiddenWords: ['秀', '禾', '木', '人', '乃', '透'], distractors: ['秀', '誘', '透', '透明', '透', '透'], difficulty: 3 },
    { id: 127, character: '誘', hiddenWords: ['言', '秀', '禾', '木', '人', '乃', '誘'], distractors: ['透', '秀', '說', '話', '語', '誰'], difficulty: 3 },
    { id: 128, character: '說', hiddenWords: ['言', '兌', '兄', '口', '儿', '說'], distractors: ['話', '語', '誰', '諸', '謝', '調'], difficulty: 3 },
    { id: 129, character: '話', hiddenWords: ['言', '舌', '千', '口', '話'], distractors: ['說', '語', '誰', '諸', '謝', '調'], difficulty: 3 },
    { id: 130, character: '語', hiddenWords: ['言', '五', '口', '吾', '語'], distractors: ['說', '話', '誰', '諸', '謝', '調'], difficulty: 3 },
    { id: 131, character: '認', hiddenWords: ['言', '人', '人', '認'], distractors: ['說', '話', '語', '誰', '諸', '謝'], difficulty: 2 },
    { id: 132, character: '誰', hiddenWords: ['言', '隹', '誰'], distractors: ['說', '話', '語', '諸', '謝', '調'], difficulty: 3 },
    { id: 133, character: '諸', hiddenWords: ['言', '者', '土', '日', '口', '諸'], distractors: ['說', '話', '語', '誰', '謝', '調'], difficulty: 3 },
    { id: 134, character: '謝', hiddenWords: ['言', '身', '寸', '謝'], distractors: ['說', '話', '語', '誰', '諸', '調'], difficulty: 3 },
    { id: 135, character: '調', hiddenWords: ['言', '周', '月', '口', '調'], distractors: ['說', '話', '語', '誰', '諸', '謝'], difficulty: 3 },
    { id: 136, character: '課', hiddenWords: ['言', '果', '日', '口', '木', '人', '課'], distractors: ['說', '話', '語', '誰', '諸', '謝'], difficulty: 3 },
    { id: 137, character: '果', hiddenWords: ['日', '口', '木', '人', '果'], distractors: ['課', '棵', '顆', '裸', '巢', '彙'], difficulty: 2 },
    { id: 138, character: '棵', hiddenWords: ['木', '人', '果', '日', '口', '棵'], distractors: ['課', '果', '顆', '裸', '巢', '彙'], difficulty: 3 },
    { id: 139, character: '顆', hiddenWords: ['果', '日', '口', '木', '人', '頁', '顆'], distractors: ['課', '果', '棵', '裸', '顏', '顛'], difficulty: 3 },
    { id: 140, character: '裸', hiddenWords: ['衣', '果', '日', '口', '木', '人', '裸'], distractors: ['課', '果', '棵', '顆', '裏', '裹'], difficulty: 3 },
    { id: 141, character: '裏', hiddenWords: ['衣', '里', '田', '口', '裏'], distractors: ['裸', '裹', '裏', '理', '埋', '量'], difficulty: 3 },
    { id: 142, character: '裹', hiddenWords: ['衣', '果', '日', '口', '木', '人', '裹'], distractors: ['裸', '裏', '裹', '課', '棵', '顆'], difficulty: 3 },
    { id: 143, character: '里', hiddenWords: ['田', '口', '土', '里'], distractors: ['理', '埋', '量', '童', '厘', '野'], difficulty: 2 },
    { id: 144, character: '理', hiddenWords: ['王', '里', '田', '口', '土', '理'], distractors: ['里', '埋', '量', '童', '厘', '野'], difficulty: 3 },
    { id: 145, character: '埋', hiddenWords: ['土', '里', '田', '口', '埋'], distractors: ['里', '理', '量', '童', '厘', '野'], difficulty: 3 },
    { id: 146, character: '量', hiddenWords: ['日', '口', '里', '田', '土', '量'], distractors: ['里', '理', '埋', '童', '厘', '野'], difficulty: 3 },
    { id: 147, character: '童', hiddenWords: ['立', '里', '田', '口', '土', '童'], distractors: ['里', '理', '埋', '量', '厘', '野'], difficulty: 3 },
    { id: 148, character: '厘', hiddenWords: ['厂', '里', '田', '口', '土', '厘'], distractors: ['里', '理', '埋', '量', '童', '野'], difficulty: 3 },
    { id: 149, character: '野', hiddenWords: ['里', '田', '口', '土', '予', '野'], distractors: ['里', '理', '埋', '量', '童', '厘'], difficulty: 3 },
    { id: 150, character: '予', hiddenWords: ['予'], distractors: ['矛', '柔', '序', '預', '抒', '紓'], difficulty: 2 },
    { id: 151, character: '矛', hiddenWords: ['矛'], distractors: ['予', '柔', '茅', '矜', '揉', '蹂'], difficulty: 2 },
    { id: 152, character: '柔', hiddenWords: ['矛', '木', '人', '柔'], distractors: ['予', '矛', '茅', '矜', '揉', '蹂'], difficulty: 3 },
    { id: 153, character: '茅', hiddenWords: ['草', '矛', '茅'], distractors: ['予', '矛', '柔', '矜', '揉', '蹂'], difficulty: 3 },
    { id: 154, character: '矜', hiddenWords: ['矛', '今', '人', '矜'], distractors: ['予', '矛', '柔', '茅', '揉', '蹂'], difficulty: 3 },
    { id: 155, character: '揉', hiddenWords: ['手', '矛', '木', '人', '柔', '揉'], distractors: ['予', '矛', '柔', '茅', '矜', '蹂'], difficulty: 3 },
    { id: 156, character: '蹂', hiddenWords: ['足', '矛', '木', '人', '柔', '蹂'], distractors: ['予', '矛', '柔', '茅', '矜', '揉'], difficulty: 3 },
    { id: 157, character: '足', hiddenWords: ['口', '足'], distractors: ['走', '是', '促', '捉', '提', '跑'], difficulty: 2 },
    { id: 158, character: '走', hiddenWords: ['土', '走'], distractors: ['足', '是', '徒', '陡', '起', '超'], difficulty: 2 },
    { id: 159, character: '是', hiddenWords: ['日', '口', '疋', '是'], distractors: ['足', '走', '提', '題', '匙', '堤'], difficulty: 2 },
    { id: 160, character: '提', hiddenWords: ['手', '是', '日', '口', '疋', '提'], distractors: ['足', '走', '是', '題', '匙', '堤'], difficulty: 3 },

    // ========== 難度3：進階挑戰（161-200關：字中找字，重疊干擾項增加，需要仔細觀察） ==========
    { id: 161, character: '題', hiddenWords: ['是', '日', '口', '疋', '頁', '題'], distractors: ['足', '走', '提', '匙', '堤', '顥'], difficulty: 3 },
    { id: 162, character: '匙', hiddenWords: ['是', '日', '口', '疋', '匕', '匙'], distractors: ['足', '走', '提', '題', '堤', '匙'], difficulty: 3 },
    { id: 163, character: '堤', hiddenWords: ['土', '是', '日', '口', '疋', '堤'], distractors: ['足', '走', '是', '提', '題', '匙'], difficulty: 3 },
    { id: 164, character: '頁', hiddenWords: ['口', '貝', '頁'], distractors: ['頂', '項', '順', '須', '頑', '顧'], difficulty: 2 },
    { id: 165, character: '頂', hiddenWords: ['丁', '頁', '口', '貝', '頂'], distractors: ['項', '順', '須', '頑', '顧', '頓'], difficulty: 3 },
    { id: 166, character: '項', hiddenWords: ['工', '頁', '口', '貝', '項'], distractors: ['頂', '順', '須', '頑', '顧', '頓'], difficulty: 3 },
    { id: 167, character: '順', hiddenWords: ['川', '頁', '口', '貝', '順'], distractors: ['頂', '項', '順', '須', '頑', '顧'], difficulty: 3 },
    { id: 168, character: '須', hiddenWords: ['彡', '頁', '口', '貝', '須'], distractors: ['頂', '項', '順', '頑', '顧', '頓'], difficulty: 3 },
    { id: 169, character: '頑', hiddenWords: ['元', '儿', '頁', '口', '貝', '頑'], distractors: ['頂', '項', '順', '須', '顧', '頓'], difficulty: 3 },
    { id: 170, character: '顧', hiddenWords: ['雇', '戶', '頁', '口', '貝', '顧'], distractors: ['頂', '項', '順', '須', '頑', '頓'], difficulty: 3 },
    { id: 171, character: '頓', hiddenWords: ['屯', '頁', '口', '貝', '頓'], distractors: ['頂', '項', '順', '須', '頑', '顧'], difficulty: 3 },
    { id: 172, character: '屯', hiddenWords: ['屯'], distractors: ['純', '頓', '噸', '鈍', '囤', '沌'], difficulty: 2 },
    { id: 173, character: '純', hiddenWords: ['糸', '屯', '純'], distractors: ['頓', '噸', '鈍', '囤', '沌', '純'], difficulty: 3 },
    { id: 174, character: '噸', hiddenWords: ['口', '屯', '噸'], distractors: ['純', '頓', '鈍', '囤', '沌', '噸'], difficulty: 3 },
    { id: 175, character: '鈍', hiddenWords: ['金', '屯', '鈍'], distractors: ['純', '頓', '噸', '囤', '沌', '鈍'], difficulty: 3 },
    { id: 176, character: '囤', hiddenWords: ['口', '屯', '囤'], distractors: ['純', '頓', '噸', '鈍', '沌', '囤'], difficulty: 3 },
    { id: 177, character: '沌', hiddenWords: ['水', '屯', '沌'], distractors: ['純', '頓', '噸', '鈍', '囤', '沌'], difficulty: 3 },
    { id: 178, character: '貝', hiddenWords: ['口', '貝'], distractors: ['見', '具', '真', '負', '貞', '頁'], difficulty: 2 },
    { id: 179, character: '見', hiddenWords: ['口', '儿', '見'], distractors: ['貝', '具', '真', '規', '視', '覓'], difficulty: 2 },
    { id: 180, character: '具', hiddenWords: ['口', '貝', '具'], distractors: ['見', '真', '俱', '惧', '颶', '縝'], difficulty: 3 },
    { id: 181, character: '真', hiddenWords: ['口', '貝', '具', '真'], distractors: ['見', '鎮', '縝', '顛', '慎', '顛'], difficulty: 3 },
    { id: 182, character: '負', hiddenWords: ['人', '口', '貝', '負'], distractors: ['貞', '頁', '貪', '貧', '責', '賢'], difficulty: 3 },
    { id: 183, character: '貞', hiddenWords: ['卜', '口', '貝', '貞'], distractors: ['負', '頁', '貪', '貧', '責', '賢'], difficulty: 3 },
    { id: 184, character: '貪', hiddenWords: ['今', '人', '口', '貝', '貪'], distractors: ['負', '貞', '頁', '貧', '責', '賢'], difficulty: 3 },
    { id: 185, character: '貧', hiddenWords: ['分', '八', '刀', '口', '貝', '貧'], distractors: ['負', '貞', '頁', '貪', '責', '賢'], difficulty: 3 },
    { id: 186, character: '責', hiddenWords: ['土', '口', '貝', '責'], distractors: ['負', '貞', '頁', '貪', '貧', '賢'], difficulty: 3 },
    { id: 187, character: '賢', hiddenWords: ['臣', '口', '貝', '賢'], distractors: ['負', '貞', '頁', '貪', '貧', '責'], difficulty: 3 },
    { id: 188, character: '臣', hiddenWords: ['臣'], distractors: ['巨', '臨', '監', '賢', '頤', '姬'], difficulty: 2 },
    { id: 189, character: '臨', hiddenWords: ['臣', '口', '臨'], distractors: ['巨', '監', '賢', '頤', '覽', '藍'], difficulty: 3 },
    { id: 190, character: '監', hiddenWords: ['臣', '口', '皿', '監'], distractors: ['巨', '臨', '賢', '藍', '籃', '艦'], difficulty: 3 },
    { id: 191, character: '覽', hiddenWords: ['臣', '口', '見', '儿', '覽'], distractors: ['巨', '臨', '監', '藍', '籃', '艦'], difficulty: 3 },
    { id: 192, character: '藍', hiddenWords: ['草', '臣', '口', '皿', '監', '藍'], distractors: ['巨', '臨', '監', '覽', '籃', '艦'], difficulty: 3 },
    { id: 193, character: '籃', hiddenWords: ['竹', '臣', '口', '皿', '監', '籃'], distractors: ['巨', '臨', '監', '覽', '藍', '艦'], difficulty: 3 },
    { id: 194, character: '艦', hiddenWords: ['舟', '臣', '口', '皿', '監', '艦'], distractors: ['巨', '臨', '監', '覽', '藍', '籃'], difficulty: 3 },
    { id: 195, character: '舟', hiddenWords: ['舟'], distractors: ['丹', '般', '船', '航', '艦', '盤'], difficulty: 2 },
    { id: 196, character: '般', hiddenWords: ['舟', '般'], distractors: ['丹', '船', '航', '盤', '搬', '瘢'], difficulty: 3 },
    { id: 197, character: '船', hiddenWords: ['舟', '口', '船'], distractors: ['丹', '般', '航', '盤', '搬', '艘'], difficulty: 3 },
    { id: 198, character: '航', hiddenWords: ['舟', '亢', '航'], distractors: ['丹', '般', '船', '盤', '炕', '杭'], difficulty: 3 },
    { id: 199, character: '盤', hiddenWords: ['舟', '般', '皿', '盤'], distractors: ['丹', '船', '航', '監', '盟', '盛'], difficulty: 3 },
    { id: 200, character: '皿', hiddenWords: ['皿'], distractors: ['血', '盟', '盛', '益', '盒', '盔'], difficulty: 2 },

];
