const levelData = [
    // ========== 難度1：入門階段（1-40關：獨體字與極簡結構，找出2-4個隱藏字） ==========
    { id: 1, character: '大', hiddenWords: ['人', '大'], distractors: ['天', '太', '犬', '木', '个'], difficulty: 1 },
    { id: 2, character: '天', hiddenWords: ['大', '人', '天'], distractors: ['夫', '太', '夭', '开', '无'], difficulty: 1 },
    { id: 3, character: '太', hiddenWords: ['大', '人', '太'], distractors: ['天', '犬', '木', '本', '头'], difficulty: 1 },
    { id: 4, character: '犬', hiddenWords: ['大', '人', '犬'], distractors: ['太', '天', '伏', '尤', '拔'], difficulty: 1 },
    { id: 5, character: '木', hiddenWords: ['木', '人'], distractors: ['本', '未', '末', '术', '禾'], difficulty: 1 },
    { id: 6, character: '本', hiddenWords: ['木', '人', '本'], distractors: ['未', '末', '术', '体', '笨'], difficulty: 1 },
    { id: 7, character: '未', hiddenWords: ['木', '人', '未'], distractors: ['末', '本', '朱', '味', '妹'], difficulty: 1 },
    { id: 8, character: '末', hiddenWords: ['木', '人', '末'], distractors: ['未', '本', '抹', '沫', '茉'], difficulty: 1 },
    { id: 9, character: '禾', hiddenWords: ['木', '人', '禾'], distractors: ['千', '千', '和', '秋', '秀'], difficulty: 1 },
    { id: 10, character: '米', hiddenWords: ['木', '人', '米'], distractors: ['来', '迷', '眯', '粉', '粒'], difficulty: 1 },
    { id: 11, character: '人', hiddenWords: ['人'], distractors: ['个', '从', '众', '大', '天', '入', '八'], difficulty: 1 },
    { id: 12, character: '从', hiddenWords: ['人', '从'], distractors: ['众', '丛', '队', '闪', '人'], difficulty: 1 },
    { id: 13, character: '众', hiddenWords: ['人', '从', '众'], distractors: ['丛', '聚', '大', '天', '太'], difficulty: 1 },
    { id: 14, character: '火', hiddenWords: ['人', '火'], distractors: ['灭', '灯', '灰', '大', '太'], difficulty: 1 },
    { id: 15, character: '灭', hiddenWords: ['火', '人', '灭'], distractors: ['大', '天', '灰', '灾', '灵'], difficulty: 1 },
    { id: 16, character: '灰', hiddenWords: ['火', '人', '灰'], distractors: ['灭', '炭', '恢', '大', '友'], difficulty: 1 },
    { id: 17, character: '闪', hiddenWords: ['门', '人', '闪'], distractors: ['问', '间', '闷', '闭', '闯'], difficulty: 1 },
    { id: 18, character: '闭', hiddenWords: ['门', '才', '闭'], distractors: ['闪', '问', '间', '闷', '闲'], difficulty: 1 },
    { id: 19, character: '问', hiddenWords: ['门', '口', '问'], distractors: ['闪', '间', '闷', '闻', '闯'], difficulty: 1 },
    { id: 20, character: '间', hiddenWords: ['门', '日', '口', '间'], distractors: ['问', '闪', '闷', '简', '润'], difficulty: 1 },
    { id: 21, character: '闷', hiddenWords: ['门', '心', '闷'], distractors: ['闪', '问', '间', '闭', '闹'], difficulty: 1 },
    { id: 22, character: '闯', hiddenWords: ['门', '马', '闯'], distractors: ['闪', '问', '间', '闭', '闲'], difficulty: 1 },
    { id: 23, character: '牛', hiddenWords: ['牛'], distractors: ['午', '告', '先', '牢', '牧', '件'], difficulty: 1 },
    { id: 24, character: '牢', hiddenWords: ['牛', '牢'], distractors: ['穴', '空', '牵', '件', '犁'], difficulty: 1 },
    { id: 25, character: '牧', hiddenWords: ['牛', '牧'], distractors: ['放', '收', '攻', '特', '物'], difficulty: 1 },
    { id: 26, character: '物', hiddenWords: ['牛', '勿', '物'], distractors: ['匆', '易', '吻', '特', '牲'], difficulty: 1 },
    { id: 27, character: '特', hiddenWords: ['牛', '寺', '寸', '特'], distractors: ['持', '等', '待', '侍', '詩'], difficulty: 1 },
    { id: 28, character: '王', hiddenWords: ['王'], distractors: ['玉', '主', '弄', '皇', '旺', '全'], difficulty: 1 },
    { id: 29, character: '玉', hiddenWords: ['王', '玉'], distractors: ['主', '国', '宝', '莹', '璧'], difficulty: 1 },
    { id: 30, character: '主', hiddenWords: ['王', '主'], distractors: ['玉', '注', '住', '柱', '往'], difficulty: 1 },
    { id: 31, character: '弄', hiddenWords: ['王', '开', '弄'], distractors: ['异', '弃', '葬', '弊', '算'], difficulty: 1 },
    { id: 32, character: '皇', hiddenWords: ['白', '口', '王', '皇'], distractors: ['煌', '凰', '泉', '腺', '魄'], difficulty: 1 },
    { id: 33, character: '全', hiddenWords: ['人', '大', '王', '全'], distractors: ['金', '企', '令', '合', '仓'], difficulty: 1 },
    { id: 34, character: '口', hiddenWords: ['口'], distractors: ['日', '田', '目', '白', '石', '右'], difficulty: 1 },
    { id: 35, character: '古', hiddenWords: ['十', '口', '古'], distractors: ['舌', '克', '估', '故', '胡'], difficulty: 1 },
    { id: 36, character: '右', hiddenWords: ['口', '右'], distractors: ['左', '石', '若', '占', '佑'], difficulty: 1 },
    { id: 37, character: '占', hiddenWords: ['卜', '口', '占'], distractors: ['点', '沾', '站', '战', '钻'], difficulty: 1 },
    { id: 38, character: '召', hiddenWords: ['刀', '口', '召'], distractors: ['招', '沼', '超', '紹', '迢'], difficulty: 1 },
    { id: 39, character: '只', hiddenWords: ['口', '八', '只'], distractors: ['识', '炽', '织', '职', '积'], difficulty: 1 },
    { id: 40, character: '兄', hiddenWords: ['口', '儿', '兄'], distractors: ['兑', '克', '兢', '況', '祝'], difficulty: 1 }
];