const levelData = [
    // ========== 難度1：入門階段（1-40關：獨體字與極簡結構，找出2-4個隱藏字） ==========
    { id: 1, character: '大', hiddenWords: ['人', '大'], distractors: ['天', '太', '犬', '木', '个'], difficulty: 1 },
    { id: 2, character: '天', hiddenWords: ['大', '人', '天'], distractors: ['夫', '太', '夭', '开', '无'], difficulty: 1 },
    { id: 3, character: '太', hiddenWords: ['大', '人', '太'], distractors: ['天', '犬', '木', '本', '头'], difficulty: 1 },
    { id: 4, character: '犬', hiddenWords: ['大', '人', '犬'], distractors: ['太', '天', '伏', '尤', '拔'], difficulty: 1 },
    { id: 5, character: '木', hiddenWords: ['木', '人'], distractors: ['本', '未', '末', '术', '禾'], difficulty: 1 },
    { id: 6, character: '本', hiddenWords: ['木', '人', '本'], distractors: ['未', '末', '术', '体', '笨'], difficulty: 1 },
    { id: 7, character: '未', hiddenWords: ['木', '人', '未'], distractors: ['末', '本', '朱', '味', '妹'], difficulty: 1 },
    { id: 8, character: '末', hiddenWords: ['木', '人', '末'], distractors: ['未', '本', '抹', '沫', '茉'], difficulty: 1 },
    { id: 9, character: '禾', hiddenWords: ['木', '人', '禾'], distractors: ['千', '千', '和', '秋', '秀'], difficulty: 1 },
    { id: 10, character: '米', hiddenWords: ['木', '人', '米'], distractors: ['来', '迷', '眯', '粉', '粒'], difficulty: 1 },
    { id: 11, character: '人', hiddenWords: ['人'], distractors: ['个', '从', '众', '大', '天', '入', '八'], difficulty: 1 },
    { id: 12, character: '从', hiddenWords: ['人', '从'], distractors: ['众', '丛', '队', '闪', '人'], difficulty: 1 },
    { id: 13, character: '众', hiddenWords: ['人', '从', '众'], distractors: ['丛', '聚', '大', '天', '太'], difficulty: 1 },
    { id: 14, character: '火', hiddenWords: ['人', '火'], distractors: ['灭', '灯', '灰', '大', '太'], difficulty: 1 },
    { id: 15, character: '灭', hiddenWords: ['火', '人', '灭'], distractors: ['大', '天', '灰', '灾', '灵'], difficulty: 1 },
    { id: 16, character: '灰', hiddenWords: ['火', '人', '灰'], distractors: ['灭', '炭', '恢', '大', '友'], difficulty: 1 },
    { id: 17, character: '闪', hiddenWords: ['门', '人', '闪'], distractors: ['问', '间', '闷', '闭', '闯'], difficulty: 1 },
    { id: 18, character: '闭', hiddenWords: ['门', '才', '闭'], distractors: ['闪', '问', '间', '闷', '闲'], difficulty: 1 },
    { id: 19, character: '问', hiddenWords: ['门', '口', '问'], distractors: ['闪', '间', '闷', '闻', '闯'], difficulty: 1 },
    { id: 20, character: '间', hiddenWords: ['门', '日', '口', '间'], distractors: ['问', '闪', '闷', '简', '润'], difficulty: 1 },
    { id: 21, character: '闷', hiddenWords: ['门', '心', '闷'], distractors: ['闪', '问', '间', '闭', '闹'], difficulty: 1 },
    { id: 22, character: '闯', hiddenWords: ['门', '马', '闯'], distractors: ['闪', '问', '间', '闭', '闲'], difficulty: 1 },
    { id: 23, character: '牛', hiddenWords: ['牛'], distractors: ['午', '告', '先', '牢', '牧', '件'], difficulty: 1 },
    { id: 24, character: '牢', hiddenWords: ['牛', '牢'], distractors: ['穴', '空', '牵', '件', '犁'], difficulty: 1 },
    { id: 25, character: '牧', hiddenWords: ['牛', '牧'], distractors: ['放', '收', '攻', '特', '物'], difficulty: 1 },
    { id: 26, character: '物', hiddenWords: ['牛', '勿', '物'], distractors: ['匆', '易', '吻', '特', '牲'], difficulty: 1 },
    { id: 27, character: '特', hiddenWords: ['牛', '寺', '寸', '特'], distractors: ['持', '等', '待', '侍', '詩'], difficulty: 1 },
    { id: 28, character: '王', hiddenWords: ['王'], distractors: ['玉', '主', '弄', '皇', '旺', '全'], difficulty: 1 },
    { id: 29, character: '玉', hiddenWords: ['王', '玉'], distractors: ['主', '国', '宝', '莹', '璧'], difficulty: 1 },
    { id: 30, character: '主', hiddenWords: ['王', '主'], distractors: ['玉', '注', '住', '柱', '往'], difficulty: 1 },
    { id: 31, character: '弄', hiddenWords: ['王', '开', '弄'], distractors: ['异', '弃', '葬', '弊', '算'], difficulty: 1 },
    { id: 32, character: '皇', hiddenWords: ['白', '口', '王', '皇'], distractors: ['煌', '凰', '泉', '腺', '魄'], difficulty: 1 },
    { id: 33, character: '全', hiddenWords: ['人', '大', '王', '全'], distractors: ['金', '企', '令', '合', '仓'], difficulty: 1 },
    { id: 34, character: '口', hiddenWords: ['口'], distractors: ['日', '田', '目', '白', '石', '右'], difficulty: 1 },
    { id: 35, character: '古', hiddenWords: ['十', '口', '古'], distractors: ['舌', '克', '估', '故', '胡'], difficulty: 1 },
    { id: 36, character: '右', hiddenWords: ['口', '右'], distractors: ['左', '石', '若', '占', '佑'], difficulty: 1 },
    { id: 37, character: '占', hiddenWords: ['卜', '口', '占'], distractors: ['点', '沾', '站', '战', '钻'], difficulty: 1 },
    { id: 38, character: '召', hiddenWords: ['刀', '口', '召'], distractors: ['招', '沼', '超', '紹', '迢'], difficulty: 1 },
    { id: 39, character: '只', hiddenWords: ['口', '八', '只'], distractors: ['识', '炽', '织', '职', '积'], difficulty: 1 },
    { id: 40, character: '兄', hiddenWords: ['口', '儿', '兄'], distractors: ['兑', '克', '兢', '況', '祝'], difficulty: 1 },

    // ========== 難度2：基礎階段（41-80關：標準左右/上下結構，拆解出2-4個清晰字） ==========
    { id: 41, character: '休', hiddenWords: ['人', '木', '休'], distractors: ['体', '沐', '保', '仆', '估', '伴'], difficulty: 2 },
    { id: 42, character: '体', hiddenWords: ['人', '本', '木', '体'], distractors: ['休', '笨', '体', '估', '仗', '佃'], difficulty: 2 },
    { id: 43, character: '位', hiddenWords: ['人', '立', '位'], distractors: ['拉', '泣', '粒', '垃', '陪', '焙'], difficulty: 2 },
    { id: 44, character: '估', hiddenWords: ['人', '古', '十', '口', '估'], distractors: ['枯', '姑', '故', '胡', '做', '佑'], difficulty: 2 },
    { id: 45, character: '伙', hiddenWords: ['人', '火', '伙'], distractors: ['秋', '伴', '队', '闪', '燃', '煬'], difficulty: 2 },
    { id: 46, character: '何', hiddenWords: ['人', '可', '口', '何'], distractors: ['河', '苛', '荷', '呵', '奇', '倚'], difficulty: 2 },
    { id: 47, character: '但', hiddenWords: ['人', '旦', '日', '口', '但'], distractors: ['担', '坦', '胆', '袒', '查', '理'], difficulty: 2 },
    { id: 48, character: '伯', hiddenWords: ['人', '白', '口', '伯'], distractors: ['怕', '拍', '迫', '舶', '柏', '泉'], difficulty: 2 },
    { id: 49, character: '仲', hiddenWords: ['人', '中', '口', '仲'], distractors: ['冲', '种', '钟', '肿', '串', '伸'], difficulty: 2 },
    { id: 50, character: '伸', hiddenWords: ['人', '申', '田', '口', '伸'], distractors: ['神', '绅', '审', '砷', '呻', '坤'], difficulty: 2 },
    { id: 51, character: '尖', hiddenWords: ['小', '大', '人', '尖'], distractors: ['尘', '卡', '少', '劣', '光', '省'], difficulty: 2 },
    { id: 52, character: '尘', hiddenWords: ['小', '土', '尘'], distractors: ['尖', '堂', '坐', '聖', '壁', '墨'], difficulty: 2 },
    { id: 53, character: '卡', hiddenWords: ['上', '下', '卡'], distractors: ['尖', '卡', '占', '卢', '卞', '乒'], difficulty: 2 },
    { id: 54, character: '引', hiddenWords: ['弓', '引'], distractors: ['张', '弥', '弦', '弹', '强', '弘'], difficulty: 2 },
    { id: 55, character: '北', hiddenWords: ['匕', '北'], distractors: ['此', '些', '背', '兆', '非', '比'], difficulty: 2 },
    { id: 56, character: '明', hiddenWords: ['日', '月', '口', '明'], distractors: ['朋', '晶', '晃', '昆', '昌', '盟'], difficulty: 2 },
    { id: 57, character: '朋', hiddenWords: ['月', '朋'], distractors: ['明', '棚', '蹦', '崩', '绷', '塑'], difficulty: 2 },
    { id: 58, character: '岩', hiddenWords: ['山', '石', '口', '岩'], distractors: ['岸', '炭', '宕', '矿', '研', '碧'], difficulty: 2 },
    { id: 59, character: '島', hiddenWords: ['山', '鸟', '岛'], distractors: ['乌', '鸣', '捣', '鸭', '鸠', '鸾'], difficulty: 2 },
    { id: 60, character: '泉', hiddenWords: ['白', '水', '口', '泉'], distractors: ['腺', '原', '愿', '線', '漂', '淼'], difficulty: 2 },
    { id: 61, character: '林', hiddenWords: ['木', '人', '林'], distractors: ['森', '淋', '麻', '楚', '焚', '禁'], difficulty: 2 },
    { id: 62, character: '森', hiddenWords: ['木', '人', '林', '森'], distractors: ['淋', '淼', '焱', '磊', '焱', '蓬'], difficulty: 2 },
    { id: 63, character: '相', hiddenWords: ['木', '目', '人', '口', '相'], distractors: ['想', '箱', '霜', '湘', '廂', '柏'], difficulty: 2 },
    { id: 64, character: '杳', hiddenWords: ['木', '日', '人', '口', '杳'], distractors: ['查', '杏', '香', '杳', '李', '杰'], difficulty: 2 },
    { id: 65, character: '析', hiddenWords: ['木', '斤', '人', '析'], distractors: ['折', '听', '近', '匠', '欣', '斯'], difficulty: 2 },
    { id: 66, character: '村', hiddenWords: ['木', '寸', '人', '村'], distractors: ['衬', '付', '守', '討', '耐', '尋'], difficulty: 2 },
    { id: 67, character: '板', hiddenWords: ['木', '反', '人', '板'], distractors: ['饭', '返', '版', '贩', '叛', '阪'], difficulty: 2 },
    { id: 68, character: '枉', hiddenWords: ['木', '王', '人', '枉'], distractors: ['狂', '旺', '汪', '匡', '拄', '班'], difficulty: 2 },
    { id: 69, character: '松', hiddenWords: ['木', '公', '八', '人', '松'], distractors: ['讼', '颂', '翁', '蚣', '瓮', '菘'], difficulty: 2 },
    { id: 70, character: '柱', hiddenWords: ['木', '主', '王', '人', '柱'], distractors: ['注', '住', '拄', '駐', '往', '弦'], difficulty: 2 },
    { id: 71, character: '拿', hiddenWords: ['合', '手', '人', '口', '拿'], distractors: ['掌', '挚', '攀', '擎', '摹', '掰'], difficulty: 2 },
    { id: 72, character: '掰', hiddenWords: ['手', '分', '八', '刀', '掰'], distractors: ['掰', '排', '拜', '攀', '摩', '掰'], difficulty: 2 },
    { id: 73, character: '看', hiddenWords: ['手', '目', '口', '看'], distractors: ['着', '眷', '羞', '眉', '盾', '省'], difficulty: 2 },
    { id: 74, character: '盲', hiddenWords: ['亡', '目', '口', '盲'], distractors: ['荒', '忙', '茫', '妄', '忘', '望'], difficulty: 2 },
    { id: 75, character: '盯', hiddenWords: ['目', '丁', '口', '盯'], distractors: ['钉', '顶', '叮', '订', '厅', '宁'], difficulty: 2 },
    { id: 76, character: '泪', hiddenWords: ['水', '目', '口', '泪'], distractors: ['湘', '汨', '渺', '沫', '浪', '泪'], difficulty: 2 },
    { id: 77, character: '盼', hiddenWords: ['目', '分', '八', '刀', '口', '盼'], distractors: ['扮', '份', '粉', '盆', '吩', '芬'], difficulty: 2 },
    { id: 78, character: '眉', hiddenWords: ['目', '口', '眉'], distractors: ['媚', '楣', '嵋', '看', '省', '眷'], difficulty: 2 },
    { id: 79, character: '眯', hiddenWords: ['目', '米', '木', '人', '口', '眯'], distractors: ['迷', '謎', '醚', '咪', '咪', '咪'], difficulty: 2 },
    { id: 80, character: '瞇', hiddenWords: ['目', '米', '木', '人', '口', '瞇'], distractors: ['眯', '迷', '謎', '瞇', '瞇', '瞇'], difficulty: 2 },

// ========== 難度2進階：複合字形（81-100關：包圍結構、復雜重疊，需要更細心） ==========
    { id: 81, character: '杏', hiddenWords: ['木', '口', '人', '杏'], distractors: ['呆', '查', '杳', '束', '困', '固'], difficulty: 2 },
    { id: 82, character: '呆', hiddenWords: ['口', '木', '人', '呆'], distractors: ['杏', '保', '集', '架', '榮', '某'], difficulty: 2 },
    { id: 83, character: '囚', hiddenWords: ['口', '人', '囚'], distractors: ['因', '国', '四', '回', '团', '圈'], difficulty: 2 },
    { id: 84, character: '因', hiddenWords: ['口', '大', '人', '因'], distractors: ['囚', '困', '团', '园', '固', '恩'], difficulty: 2 },
    { id: 85, character: '困', hiddenWords: ['口', '木', '人', '困'], distractors: ['因', '固', '圈', '囫', '囵', '圃'], difficulty: 2 },
    { id: 86, character: '固', hiddenWords: ['口', '古', '十', '固'], distractors: ['困', '因', '锢', '箇', '個', '涸'], difficulty: 2 },
    { id: 87, character: '国', hiddenWords: ['口', '王', '玉', '国'], distractors: ['园', '围', '图', '固', '圈', '圃'], difficulty: 2 },
    { id: 88, character: '图', hiddenWords: ['口', '冬', '图'], distractors: ['国', '园', '围', '圈', '圉', '圄'], difficulty: 2 },
    { id: 89, character: '东', hiddenWords: ['木', '人', '东'], distractors: ['乐', '栋', '陈', '冻', '练', '柬'], difficulty: 2 },
    { id: 90, character: '卡', hiddenWords: ['上', '下', '卡'], distractors: ['占', '步', '卢', '卓', '乒', '乓'], difficulty: 2 },
    { id: 91, character: '古', hiddenWords: ['十', '口', '古'], distractors: ['舌', '故', '枯', '居', '苦', '克'], difficulty: 2 },
    { id: 92, character: '克', hiddenWords: ['十', '口', '儿', '克'], distractors: ['兄', '兢', '克', '充', '兑', '吊'], difficulty: 2 },
    { id: 93, character: '合', hiddenWords: ['人', '口', '合'], distractors: ['盒', '哈', '答', '拾', '塔', '给'], difficulty: 2 },
    { id: 94, character: '吉', hiddenWords: ['士', '口', '吉'], distractors: ['志', '洁', '结', '桔', '喆', '古'], difficulty: 2 },
    { id: 95, character: '吞', hiddenWords: ['天', '大', '人', '口', '吞'], distractors: ['蚕', '歪', '否', '杏', '呆', '吾'], difficulty: 2 },
    { id: 96, character: '吾', hiddenWords: ['五', '口', '吾'], distractors: ['语', '梧', '衙', '悟', '吞', '杏'], difficulty: 2 },
    { id: 97, character: '含', hiddenWords: ['今', '人', '口', '含'], distractors: ['念', '贪', '吟', '晗', '颔', '怜'], difficulty: 2 },
    { id: 98, character: '谷', hiddenWords: ['八', '人', '口', '谷'], distractors: ['欲', '俗', '浴', '容', '裕', '卻'], difficulty: 2 },
    { id: 99, character: '杏', hiddenWords: ['木', '口', '人', '杏'], distractors: ['呆', '束', '枯', '研', '否', '各'], difficulty: 2 },
    { id: 100, character: '吳', hiddenWords: ['口', '大', '人', '吳'], distractors: ['娱', '误', '蜈', '噢', '悞', '噭'], difficulty: 2 },

    // ========== 難度2-3：中等階梯（101-160關：常見形聲與會意字，漢字結構更豐富） ==========
    { id: 101, character: '李', hiddenWords: ['木', '子', '人', '了', '李'], distractors: ['季', '杏', '柔', '婪', '孟', '仔'], difficulty: 2 },
    { id: 102, character: '季', hiddenWords: ['禾', '木', '人', '子', '了', '季'], distractors: ['李', '委', '秀', '透', '俘', '孝'], difficulty: 2 },
    { id: 103, character: '委', hiddenWords: ['禾', '女', '木', '人', '委'], distractors: ['季', '姜', '姿', '要', '魏', '矮'], difficulty: 2 },
    { id: 104, character: '姜', hiddenWords: ['羊', '女', '姜'], distractors: ['美', '羔', '羞', '姿', '妥', '娄'], difficulty: 2 },
    { id: 105, character: '姿', hiddenWords: ['次', '女', '欠', '姿'], distractors: ['资', '恣', '咨', '瓷', '羨', '盜'], difficulty: 2 },
    { id: 106, character: '絮', hiddenWords: ['如', '女', '口', '糸', '絮'], distractors: ['紧', '紫', '索', '累', '恕', '恕'], difficulty: 3 },
    { id: 107, character: '恕', hiddenWords: ['如', '女', '口', '心', '恕'], distractors: ['怒', '怨', '恕', '恐', '恋', '恕'], difficulty: 3 },
    { id: 108, character: '怨', hiddenWords: ['夕', '心', '怨'], distractors: ['怒', '恕', '恐', '悲', '急', '忽'], difficulty: 3 },
    { id: 109, character: '祭', hiddenWords: ['夕', '示', '祭'], distractors: ['察', '擦', '蔡', '際', '瘵', '穄'], difficulty: 3 },
    { id: 110, character: '禁', hiddenWords: ['林', '木', '人', '示', '禁'], distractors: ['楚', '焚', '婪', '襟', '噤', '澿'], difficulty: 3 },
    { id: 111, character: '焚', hiddenWords: ['林', '木', '人', '火', '焚'], distractors: ['禁', '楚', '婪', '梵', '婪', '婪'], difficulty: 3 },
    { id: 112, character: '楚', hiddenWords: ['林', '木', '人', '疋', '楚'], distractors: ['禁', '焚', '婪', '礎', '糊', '楚'], difficulty: 3 },
    { id: 113, character: '霖', hiddenWords: ['雨', '林', '木', '人', '霖'], distractors: ['霜', '雹', '露', '霸', '震', '霉'], difficulty: 3 },
    { id: 114, character: '露', hiddenWords: ['雨', '路', '足', '各', '口', '露'], distractors: ['霜', '雹', '霸', '霧', '靂', '霾'], difficulty: 3 },
    { id: 115, character: '霜', hiddenWords: ['雨', '木', '目', '口', '相', '霜'], distractors: ['雪', '霞', '雹', '霧', '霸', '靂'], difficulty: 3 },
    { id: 116, character: '霞', hiddenWords: ['雨', '叚', '二', '霞'], distractors: ['霜', '雹', '霸', '霧', '靂', '霾'], difficulty: 3 },
    { id: 117, character: '霸', hiddenWords: ['雨', '革', '月', '霸'], distractors: ['霜', '雹', '露', '霧', '靂', '霾'], difficulty: 3 },
    { id: 118, character: '霆', hiddenWords: ['雨', '廷', '壬', '霆'], distractors: ['雷', '震', '霉', '霍', '霓', '霎'], difficulty: 3 },
    { id: 119, character: '震', hiddenWords: ['雨', '辰', '震'], distractors: ['雷', '霆', '霉', '霍', '霓', '霎'], difficulty: 3 },
    { id: 120, character: '霉', hiddenWords: ['雨', '每', '人', '母', '霉'], distractors: ['雷', '震', '霆', '霍', '霓', '霎'], difficulty: 3 },
    { id: 121, character: '智', hiddenWords: ['知', '矢', '口', '日', '智'], distractors: ['蜘', '痴', '踟', '矩', '短', '矮'], difficulty: 3 },
    { id: 122, character: '蠢', hiddenWords: ['春', '日', '人', '虫', '蠢'], distractors: ['香', '秦', '泰', '奏', '蠢', '蠢'], difficulty: 3 },
    { id: 123, character: '香', hiddenWords: ['禾', '木', '人', '日', '口', '香'], distractors: ['季', '秀', '委', '禿', '乘', '剩'], difficulty: 2 },
    { id: 124, character: '禿', hiddenWords: ['禾', '木', '人', '几', '禿'], distractors: ['秀', '香', '季', '委', '乘', '禿'], difficulty: 2 },
    { id: 125, character: '秀', hiddenWords: ['禾', '木', '人', '乃', '秀'], distractors: ['禿', '香', '季', '委', '透', '誘'], difficulty: 2 },
    { id: 126, character: '透', hiddenWords: ['秀', '禾', '木', '人', '乃', '透'], distractors: ['秀', '誘', '透', '穿', '香', '禿'], difficulty: 3 },
    { id: 127, character: '誘', hiddenWords: ['言', '秀', '禾', '木', '人', '乃', '誘'], distractors: ['透', '秀', '說', '話', '語', '誰'], difficulty: 3 },
    { id: 128, character: '說', hiddenWords: ['言', '兌', '兄', '口', '儿', '說'], distractors: ['話', '語', '誰', '諸', '謝', '調'], difficulty: 3 },
    { id: 129, character: '話', hiddenWords: ['言', '舌', '千', '口', '話'], distractors: ['說', '語', '誰', '諸', '謝', '調'], difficulty: 3 },
    { id: 130, character: '語', hiddenWords: ['言', '五', '口', '吾', '語'], distractors: ['說', '話', '誰', '諸', '謝', '調'], difficulty: 3 },
    { id: 131, character: '認', hiddenWords: ['言', '人', '人', '認'], distractors: ['說', '話', '語', '誰', '諸', '謝'], difficulty: 2 },
    { id: 132, character: '誰', hiddenWords: ['言', '隹', '誰'], distractors: ['說', '話', '語', '諸', '謝', '調'], difficulty: 3 },
    { id: 133, character: '諸', hiddenWords: ['言', '者', '土', '日', '口', '諸'], distractors: ['說', '話', '語', '誰', '謝', '調'], difficulty: 3 },
    { id: 134, character: '謝', hiddenWords: ['言', '身', '寸', '謝'], distractors: ['說', '話', '語', '誰', '諸', '調'], difficulty: 3 },
    { id: 135, character: '調', hiddenWords: ['言', '周', '月', '口', '調'], distractors: ['說', '話', '語', '誰', '諸', '謝'], difficulty: 3 },
    { id: 136, character: '課', hiddenWords: ['言', '果', '日', '口', '木', '人', '課'], distractors: ['說', '話', '語', '誰', '諸', '謝'], difficulty: 3 },
    { id: 137, character: '果', hiddenWords: ['日', '口', '木', '人', '果'], distractors: ['課', '棵', '顆', '裸', '巢', '彙'], difficulty: 2 },
    { id: 138, character: '棵', hiddenWords: ['木', '人', '果', '日', '口', '棵'], distractors: ['課', '果', '顆', '裸', '巢', '彙'], difficulty: 3 },
    { id: 139, character: '顆', hiddenWords: ['果', '日', '口', '木', '人', '頁', '顆'], distractors: ['課', '果', '棵', '裸', '顏', '顛'], difficulty: 3 },
    { id: 140, character: '裸', hiddenWords: ['衣', '果', '日', '口', '木', '人', '裸'], distractors: ['課', '果', '棵', '顆', '裏', '裹'], difficulty: 3 },
    { id: 141, character: '裏', hiddenWords: ['衣', '里', '田', '口', '裏'], distractors: ['裸', '裹', '裏', '理', '埋', '量'], difficulty: 3 },
    { id: 142, character: '裹', hiddenWords: ['衣', '果', '日', '口', '木', '人', '裹'], distractors: ['裸', '裏', '裹', '課', '棵', '顆'], difficulty: 3 },
    { id: 143, character: '里', hiddenWords: ['田', '口', '土', '里'], distractors: ['理', '埋', '量', '童', '厘', '野'], difficulty: 2 },
    { id: 144, character: '理', hiddenWords: ['王', '里', '田', '口', '土', '理'], distractors: ['里', '埋', '量', '童', '厘', '野'], difficulty: 3 },
    { id: 145, character: '埋', hiddenWords: ['土', '里', '田', '口', '埋'], distractors: ['里', '理', '量', '童', '厘', '野'], difficulty: 3 },
    { id: 146, character: '量', hiddenWords: ['日', '口', '里', '田', '土', '量'], distractors: ['里', '理', '埋', '童', '厘', '野'], difficulty: 3 },
    { id: 147, character: '童', hiddenWords: ['立', '里', '田', '口', '土', '童'], distractors: ['里', '理', '埋', '量', '厘', '野'], difficulty: 3 },
    { id: 148, character: '厘', hiddenWords: ['厂', '里', '田', '口', '土', '厘'], distractors: ['里', '理', '埋', '量', '童', '野'], difficulty: 3 },
    { id: 149, character: '野', hiddenWords: ['里', '田', '口', '土', '予', '野'], distractors: ['里', '理', '埋', '量', '童', '厘'], difficulty: 3 },
    { id: 150, character: '予', hiddenWords: ['予'], distractors: ['矛', '柔', '序', '預', '抒', '紓'], difficulty: 2 },
    { id: 151, character: '矛', hiddenWords: ['矛'], distractors: ['予', '柔', '茅', '矜', '揉', '蹂'], difficulty: 2 },
    { id: 152, character: '柔', hiddenWords: ['矛', '木', '人', '柔'], distractors: ['予', '矛', '茅', '矜', '揉', '蹂'], difficulty: 3 },
    { id: 153, character: '茅', hiddenWords: ['草', '矛', '茅'], distractors: ['予', '矛', '柔', '矜', '揉', '蹂'], difficulty: 3 },
    { id: 154, character: '矜', hiddenWords: ['矛', '今', '人', '矜'], distractors: ['予', '矛', '柔', '茅', '揉', '蹂'], difficulty: 3 },
    { id: 155, character: '揉', hiddenWords: ['手', '矛', '木', '人', '柔', '揉'], distractors: ['予', '矛', '柔', '茅', '矜', '蹂'], difficulty: 3 },
    { id: 156, character: '蹂', hiddenWords: ['足', '矛', '木', '人', '柔', '蹂'], distractors: ['予', '矛', '柔', '茅', '矜', '揉'], difficulty: 3 },
    { id: 157, character: '足', hiddenWords: ['口', '足'], distractors: ['走', '是', '促', '捉', '提', '跑'], difficulty: 2 },
    { id: 158, character: '走', hiddenWords: ['土', '走'], distractors: ['足', '是', '徒', '陡', '起', '超'], difficulty: 2 },
    { id: 159, character: '是', hiddenWords: ['日', '口', '疋', '是'], distractors: ['足', '走', '提', '題', '匙', '堤'], difficulty: 2 },
    { id: 160, character: '提', hiddenWords: ['手', '是', '日', '口', '疋', '提'], distractors: ['足', '走', '是', '題', '匙', '堤'], difficulty: 3 },

    // ========== 難度3：進階挑戰（161-200關：字中找字，重疊干擾項增加，需要仔細觀察） ==========
    { id: 161, character: '題', hiddenWords: ['是', '日', '口', '疋', '頁', '題'], distractors: ['足', '走', '提', '匙', '堤', '顥'], difficulty: 3 },
    { id: 162, character: '匙', hiddenWords: ['是', '日', '口', '疋', '匕', '匙'], distractors: ['足', '走', '提', '題', '堤', '匙'], difficulty: 3 },
    { id: 163, character: '堤', hiddenWords: ['土', '是', '日', '口', '疋', '堤'], distractors: ['足', '走', '是', '提', '題', '匙'], difficulty: 3 },
    { id: 164, character: '頁', hiddenWords: ['口', '貝', '頁'], distractors: ['頂', '項', '順', '須', '頑', '顧'], difficulty: 2 },
    { id: 165, character: '頂', hiddenWords: ['丁', '頁', '口', '貝', '頂'], distractors: ['項', '順', '須', '頑', '顧', '頓'], difficulty: 3 },
    { id: 166, character: '項', hiddenWords: ['工', '頁', '口', '貝', '項'], distractors: ['頂', '順', '須', '頑', '顧', '頓'], difficulty: 3 },
    { id: 167, character: '順', hiddenWords: ['川', '頁', '口', '貝', '順'], distractors: ['頂', '項', '順', '須', '頑', '顧'], difficulty: 3 },
    { id: 168, character: '須', hiddenWords: ['彡', '頁', '口', '貝', '須'], distractors: ['頂', '項', '順', '頑', '顧', '頓'], difficulty: 3 },
    { id: 169, character: '頑', hiddenWords: ['元', '儿', '頁', '口', '貝', '頑'], distractors: ['頂', '項', '順', '須', '顧', '頓'], difficulty: 3 },
    { id: 170, character: '顧', hiddenWords: ['雇', '戶', '頁', '口', '貝', '顧'], distractors: ['頂', '項', '順', '須', '頑', '頓'], difficulty: 3 },
    { id: 171, character: '頓', hiddenWords: ['屯', '頁', '口', '貝', '頓'], distractors: ['頂', '項', '順', '須', '頑', '顧'], difficulty: 3 },
    { id: 172, character: '屯', hiddenWords: ['屯'], distractors: ['純', '頓', '噸', '鈍', '囤', '沌'], difficulty: 2 },
    { id: 173, character: '純', hiddenWords: ['糸', '屯', '純'], distractors: ['頓', '噸', '鈍', '囤', '沌', '純'], difficulty: 3 },
    { id: 174, character: '噸', hiddenWords: ['口', '屯', '噸'], distractors: ['純', '頓', '鈍', '囤', '沌', '噸'], difficulty: 3 },
    { id: 175, character: '鈍', hiddenWords: ['金', '屯', '鈍'], distractors: ['純', '頓', '噸', '囤', '沌', '鈍'], difficulty: 3 },
    { id: 176, character: '囤', hiddenWords: ['口', '屯', '囤'], distractors: ['純', '頓', '噸', '鈍', '沌', '囤'], difficulty: 3 },
    { id: 177, character: '沌', hiddenWords: ['水', '屯', '沌'], distractors: ['純', '頓', '噸', '鈍', '囤', '沌'], difficulty: 3 },
    { id: 178, character: '貝', hiddenWords: ['口', '貝'], distractors: ['見', '具', '真', '負', '貞', '頁'], difficulty: 2 },
    { id: 179, character: '見', hiddenWords: ['口', '儿', '見'], distractors: ['貝', '具', '真', '規', '視', '覓'], difficulty: 2 },
    { id: 180, character: '具', hiddenWords: ['口', '貝', '具'], distractors: ['見', '真', '俱', '惧', '颶', '縝'], difficulty: 3 },
    { id: 181, character: '真', hiddenWords: ['口', '貝', '具', '真'], distractors: ['見', '鎮', '縝', '顛', '慎', '顛'], difficulty: 3 },
    { id: 182, character: '負', hiddenWords: ['人', '口', '貝', '負'], distractors: ['貞', '頁', '貪', '貧', '責', '賢'], difficulty: 3 },
    { id: 183, character: '貞', hiddenWords: ['卜', '口', '貝', '貞'], distractors: ['負', '頁', '貪', '貧', '責', '賢'], difficulty: 3 },
    { id: 184, character: '貪', hiddenWords: ['今', '人', '口', '貝', '貪'], distractors: ['負', '貞', '頁', '貧', '責', '賢'], difficulty: 3 },
    { id: 185, character: '貧', hiddenWords: ['分', '八', '刀', '口', '貝', '貧'], distractors: ['負', '貞', '頁', '貪', '責', '賢'], difficulty: 3 },
    { id: 186, character: '責', hiddenWords: ['土', '口', '貝', '責'], distractors: ['負', '貞', '頁', '貪', '貧', '賢'], difficulty: 3 },
    { id: 187, character: '賢', hiddenWords: ['臣', '口', '貝', '賢'], distractors: ['負', '貞', '頁', '貪', '貧', '責'], difficulty: 3 },
    { id: 188, character: '臣', hiddenWords: ['臣'], distractors: ['巨', '臨', '監', '賢', '頤', '姬'], difficulty: 2 },
    { id: 189, character: '臨', hiddenWords: ['臣', '口', '臨'], distractors: ['巨', '監', '賢', '頤', '覽', '藍'], difficulty: 3 },
    { id: 190, character: '監', hiddenWords: ['臣', '口', '皿', '監'], distractors: ['巨', '臨', '賢', '藍', '籃', '艦'], difficulty: 3 },
    { id: 191, character: '覽', hiddenWords: ['臣', '口', '見', '儿', '覽'], distractors: ['巨', '臨', '監', '藍', '籃', '艦'], difficulty: 3 },
    { id: 192, character: '藍', hiddenWords: ['草', '臣', '口', '皿', '監', '藍'], distractors: ['巨', '臨', '監', '覽', '籃', '艦'], difficulty: 3 },
    { id: 193, character: '籃', hiddenWords: ['竹', '臣', '口', '皿', '監', '籃'], distractors: ['巨', '臨', '監', '覽', '藍', '艦'], difficulty: 3 },
    { id: 194, character: '艦', hiddenWords: ['舟', '臣', '口', '皿', '監', '艦'], distractors: ['巨', '臨', '監', '覽', '藍', '籃'], difficulty: 3 },
    { id: 195, character: '舟', hiddenWords: ['舟'], distractors: ['丹', '般', '船', '航', '艦', '盤'], difficulty: 2 },
    { id: 196, character: '般', hiddenWords: ['舟', '般'], distractors: ['丹', '船', '航', '盤', '搬', '瘢'], difficulty: 3 },
    { id: 197, character: '船', hiddenWords: ['舟', '口', '船'], distractors: ['丹', '般', '航', '盤', '搬', '艘'], difficulty: 3 },
    { id: 198, character: '航', hiddenWords: ['舟', '亢', '航'], distractors: ['丹', '般', '船', '盤', '炕', '杭'], difficulty: 3 },
    { id: 199, character: '盤', hiddenWords: ['舟', '般', '皿', '盤'], distractors: ['丹', '船', '航', '監', '盟', '盛'], difficulty: 3 },
    { id: 200, character: '皿', hiddenWords: ['皿'], distractors: ['血', '盟', '盛', '益', '盒', '盔'], difficulty: 2 },

    // ========== 難度3：中等深化（201-260關：部件重疊多，干擾項隨之增加） ==========
    { id: 201, character: '春', hiddenWords: ['日', '人', '大', '春'], distractors: ['秦', '泰', '奏', '奉', '舂', '眷', '蠢', '吞'], difficulty: 3 },
    { id: 202, character: '秦', hiddenWords: ['禾', '木', '人', '大', '秦'], distractors: ['春', '泰', '奏', '奉', '舂', '稼', '稿', '榛'], difficulty: 3 },
    { id: 203, character: '泰', hiddenWords: ['水', '人', '大', '泰'], distractors: ['春', '秦', '奏', '奉', '氽', '淼', '漆', '膝'], difficulty: 3 },
    { id: 204, character: '奏', hiddenWords: ['天', '人', '大', '奏'], distractors: ['春', '秦', '泰', '奉', '揍', '腠', '吞', '夭'], difficulty: 3 },
    { id: 205, character: '奉', hiddenWords: ['手', '人', '大', '奉'], distractors: ['春', '秦', '泰', '奏', '棒', '捧', '俸', '琫'], difficulty: 3 },
    { id: 206, character: '音', hiddenWords: ['立', '日', '口', '音'], distractors: ['意', '暗', '韻', '章', '昱', '竟', '盲', '百'], difficulty: 3 },
    { id: 207, character: '章', hiddenWords: ['立', '日', '口', '十', '章'], distractors: ['音', '意', '障', '彰', '樟', '璋', '竟', '罩'], difficulty: 3 },
    { id: 208, character: '意', hiddenWords: ['立', '日', '口', '心', '音', '意'], distractors: ['章', '億', '臆', '薏', '怠', '憨', '憩', '愁'], difficulty: 3 },
    { id: 209, character: '竟', hiddenWords: ['立', '日', '口', '儿', '竟'], distractors: ['音', '章', '意', '境', '鏡', '競', '兄', '克'], difficulty: 3 },
    { id: 210, character: '看', hiddenWords: ['手', '目', '口', '看'], distractors: ['著', '眷', '羞', '眉', '盾', '省', '瞥', '盼', '盯'], difficulty: 3 },
    { id: 211, character: '著', hiddenWords: ['草', '手', '目', '口', '看', '著'], distractors: ['看', '箸', '奢', '煮', '署', '緒', '諸', '儲'], difficulty: 3 },
    { id: 212, character: '眷', hiddenWords: ['目', '口', '人', '眷'], distractors: ['看', '著', '券', '拳', '豢', '羨', '譽', '謄'], difficulty: 3 },
    { id: 213, character: '羞', hiddenWords: ['羊', '丑', '羞'], distractors: ['看', '著', '差', '著', '羞', '詳', '鮮', '糕'], difficulty: 3 },
    { id: 214, character: '美', hiddenWords: ['羊', '大', '人', '美'], distractors: ['羔', '姜', '羞', '羨', '羹', '镁', '媄', '恙'], difficulty: 3 },
    { id: 215, character: '羔', hiddenWords: ['羊', '火', '羔'], distractors: ['美', '姜', '羞', '糕', '羹', '熬', '羔', '羔'], difficulty: 3 },
    { id: 216, character: '羹', hiddenWords: ['羊', '大', '人', '米', '木', '羹'], distractors: ['美', '羔', '羞', '羹', '羹', '糖', '糕', '羹'], difficulty: 3 },
    { id: 217, character: '羨', hiddenWords: ['羊', '大', '人', '欠', '次', '羨'], distractors: ['美', '羔', '羞', '羨', '羨', '盜', '姿', '羨'], difficulty: 3 },
    { id: 218, character: '盜', hiddenWords: ['次', '欠', '皿', '盜'], distractors: ['羨', '瓷', '姿', '諮', '盜', '盛', '盟', '益'], difficulty: 3 },
    { id: 219, character: '盛', hiddenWords: ['皿', '盛'], distractors: ['盜', '盟', '益', '盒', '盔', '盞', '盤', '監'], difficulty: 3 },
    { id: 220, character: '盟', hiddenWords: ['日', '口', '月', '皿', '明', '盟'], distractors: ['盜', '盛', '益', '盒', '盔', '盞', '盤', '監'], difficulty: 3 },
    { id: 221, character: '益', hiddenWords: ['八', '皿', '益'], distractors: ['盜', '盛', '盟', '盒', '盔', '盞', '溢', '縊'], difficulty: 3 },
    { id: 222, character: '盒', hiddenWords: ['人', '口', '合', '皿', '盒'], distractors: ['盜', '盛', '盟', '益', '盔', '盞', '哈', '答'], difficulty: 3 },
    { id: 223, character: '盔', hiddenWords: ['大', '人', '皿', '盔'], distractors: ['盜', '盛', '盟', '益', '盒', '盞', '魁', '塊'], difficulty: 3 },
    { id: 224, character: '盞', hiddenWords: ['戈', '皿', '盞'], distractors: ['盜', '盛', '盟', '益', '盒', '盔', '殘', '踐'], difficulty: 3 },
    { id: 225, character: '尖', hiddenWords: ['小', '大', '人', '尖'], distractors: ['塵', '卡', '少', '劣', '光', '省', '雀', '尖'], difficulty: 3 },
    { id: 226, character: '塵', hiddenWords: ['小', '土', '塵'], distractors: ['尖', '堂', '坐', '聖', '壁', '墨', '墾', '墊'], difficulty: 3 },
    { id: 227, character: '雀', hiddenWords: ['小', '隹', '雀'], distractors: ['尖', '雅', '集', '雇', '雁', '焦', '截', '准'], difficulty: 3 },
    { id: 228, character: '集', hiddenWords: ['隹', '木', '人', '集'], distractors: ['雀', '雅', '雇', '雁', '焦', '椎', '催', '雄'], difficulty: 3 },
    { id: 229, character: '雅', hiddenWords: ['隹', '雅'], distractors: ['雀', '集', '雇', '雁', '焦', '稚', '雌', '雕'], difficulty: 3 },
    { id: 230, character: '雇', hiddenWords: ['戶', '隹', '雇'], distractors: ['雀', '集', '雅', '雁', '焦', '顧', '肇', '扉'], difficulty: 3 },
    { id: 231, character: '雁', hiddenWords: ['厂', '隹', '人', '雁'], distractors: ['雀', '集', '雅', '雇', '焦', '鷹', '應', '膺'], difficulty: 3 },
    { id: 232, character: '焦', hiddenWords: ['隹', '火', '焦'], distractors: ['雀', '集', '雅', '雇', '雁', '瞧', '礁', '蕉'], difficulty: 3 },
    { id: 233, character: '瞧', hiddenWords: ['目', '口', '隹', '火', '焦', '瞧'], distractors: ['雀', '集', '雅', '雇', '雁', '焦', '礁', '蕉', '憔', '瞧'], difficulty: 3 },
    { id: 234, character: '礁', hiddenWords: ['石', '口', '隹', '火', '焦', '礁'], distractors: ['雀', '集', '雅', '雇', '雁', '焦', '瞧', '蕉', '憔', '醮'], difficulty: 3 },
    { id: 235, character: '蕉', hiddenWords: ['草', '隹', '火', '焦', '蕉'], distractors: ['雀', '集', '雅', '雇', '雁', '焦', '瞧', '礁', '憔', '蘸'], difficulty: 3 },
    { id: 236, character: '東', hiddenWords: ['木', '人', '東'], distractors: ['樂', '棟', '陳', '凍', '練', '柬', '欄', '爛'], difficulty: 3 },
    { id: 237, character: '棟', hiddenWords: ['木', '人', '東', '棟'], distractors: ['樂', '陳', '凍', '練', '柬', '欄', '爛', '棟'], difficulty: 3 },
    { id: 238, character: '陳', hiddenWords: ['東', '木', '人', '陳'], distractors: ['樂', '棟', '凍', '練', '柬', '陣', '陸', '隊'], difficulty: 3 },
    { id: 239, character: '凍', hiddenWords: ['東', '木', '人', '凍'], distractors: ['樂', '棟', '陳', '練', '柬', '冰', '冷', '涼'], difficulty: 3 },
    { id: 240, character: '練', hiddenWords: ['糸', '東', '木', '人', '練'], distractors: ['樂', '棟', '陳', '凍', '柬', '絲', '線', '編'], difficulty: 3 },
    { id: 241, character: '柬', hiddenWords: ['口', '木', '人', '柬'], distractors: ['東', '揀', '煉', '柬', '柬', '柬', '柬', '柬'], difficulty: 3 },
    { id: 242, character: '揀', hiddenWords: ['手', '口', '木', '人', '柬', '揀'], distractors: ['東', '煉', '揀', '練', '棟', '陳', '凍', '柬'], difficulty: 3 },
    { id: 243, character: '煉', hiddenWords: ['火', '口', '木', '人', '柬', '煉'], distractors: ['東', '揀', '煉', '練', '棟', '陳', '凍', '柬'], difficulty: 3 },
    { id: 244, character: '西', hiddenWords: ['口', '西'], distractors: ['要', '栗', '賈', '覆', '茜', '硒', '栖', '哂'], difficulty: 3 },
    { id: 245, character: '要', hiddenWords: ['西', '口', '女', '要'], distractors: ['栗', '賈', '覆', '腰', '耍', '娶', '婪', '妥'], difficulty: 3 },
    { id: 246, character: '栗', hiddenWords: ['西', '口', '木', '人', '栗'], distractors: ['要', '賈', '覆', '粟', '票', '檁', '傈', '篥'], difficulty: 3 },
    { id: 247, character: '賈', hiddenWords: ['西', '口', '貝', '賈'], distractors: ['要', '栗', '覆', '買', '賣', '讀', '續', '贖'], difficulty: 3 },
    { id: 248, character: '覆', hiddenWords: ['西', '口', '覆'], distractors: ['要', '栗', '賈', '履', '履', '履', '履', '履'], difficulty: 3 },
    { id: 249, character: '票', hiddenWords: ['西', '口', '示', '票'], distractors: ['栗', '粟', '瓢', '嫖', '漂', '縹', '剽', '鏢'], difficulty: 3 },
    { id: 250, character: '漂', hiddenWords: ['水', '西', '口', '示', '票', '漂'], distractors: ['栗', '粟', '瓢', '嫖', '漂', '縹', '剽', '鏢'], difficulty: 3 },
    { id: 251, character: '瓢', hiddenWords: ['西', '口', '示', '票', '瓜', '瓢'], distractors: ['栗', '粟', '嫖', '漂', '縹', '剽', '鏢', '瓣'], difficulty: 3 },
    { id: 252, character: '瓜', hiddenWords: ['瓜'], distractors: ['爪', '孤', '狐', '瓢', '瓣', '呱', '抓', '爬'], difficulty: 3 },
    { id: 253, character: '孤', hiddenWords: ['子', '了', '瓜', '孤'], distractors: ['爪', '狐', '瓢', '瓣', '呱', '抓', '爬', '弧'], difficulty: 3 },
    { id: 254, character: '狐', hiddenWords: ['瓜', '狐'], distractors: ['爪', '孤', '瓢', '瓣', '呱', '抓', '爬', '弧'], difficulty: 3 },
    { id: 255, character: '瓣', hiddenWords: ['辛', '十', '口', '瓜', '瓣'], distractors: ['辨', '辯', '辦', '辭', '辟', '壁', '臂', '避'], difficulty: 3 },
    { id: 256, character: '辛', hiddenWords: ['十', '口', '辛'], distractors: ['幸', '梓', '辣', '辨', '辦', '辭', '辟', '壁'], difficulty: 3 },
    { id: 257, character: '辨', hiddenWords: ['辛', '十', '口', '辨'], distractors: ['瓣', '辯', '辦', '辭', '辟', '壁', '臂', '避'], difficulty: 3 },
    { id: 258, character: '辯', hiddenWords: ['辛', '十', '口', '言', '辯'], distractors: ['瓣', '辨', '辦', '辭', '辟', '壁', '臂', '避'], difficulty: 3 },
    { id: 259, character: '辦', hiddenWords: ['力', '辦'], distractors: ['瓣', '辨', '辯', '辭', '辟', '壁', '臂', '避'], difficulty: 3 },
    { id: 260, character: '力', hiddenWords: ['力'], distractors: ['刀', '九', '方', '加', '劣', '男', '功', '務', '助', '劫'], difficulty: 3 },

    // ========== 難度3進階：結構復雜度拉滿（261-300關：干擾項高達10-12個，極其考驗眼力） ==========
    { id: 261, character: '男', hiddenWords: ['田', '口', '力', '男'], distractors: ['劣', '加', '功', '務', '助', '劫', '勇', '舅', '甥', '虜'], difficulty: 3 },
    { id: 262, character: '劣', hiddenWords: ['少', '小', '力', '劣'], distractors: ['男', '加', '功', '務', '助', '劫', '勇', '尖', '塵', '雀'], difficulty: 3 },
    { id: 263, character: '加', hiddenWords: ['力', '口', '加'], distractors: ['男', '劣', '功', '務', '助', '劫', '勇', '賀', '架', '咖'], difficulty: 3 },
    { id: 264, character: '賀', hiddenWords: ['力', '口', '加', '貝', '賀'], distractors: ['男', '劣', '功', '務', '助', '架', '賀', '資', '賈', '賡'], difficulty: 3 },
    { id: 265, character: '架', hiddenWords: ['力', '口', '加', '木', '人', '架'], distractors: ['男', '劣', '功', '務', '助', '賀', '架', '枷', '茄', '袈'], difficulty: 3 },
    { id: 266, character: '泉', hiddenWords: ['白', '口', '水', '泉'], distractors: ['腺', '原', '願', '線', '漂', '淼', '源', '瀑', '潭', '溪', '漁', '潔'], difficulty: 3 },
    { id: 267, character: '原', hiddenWords: ['厂', '白', '口', '水', '泉', '原'], distractors: ['腺', '願', '線', '漂', '淼', '源', '瀑', '潭', '溪', '源', '願', '源'], difficulty: 3 },
    { id: 268, character: '願', hiddenWords: ['厂', '白', '口', '水', '泉', '原', '頁', '貝', '願'], distractors: ['腺', '線', '漂', '源', '瀑', '顧', '顛', '顥', '顫', '顯'], difficulty: 3 },
    { id: 269, character: '白', hiddenWords: ['口', '白'], distractors: ['百', '日', '目', '田', '由', '甲', '申', '自', '皇', '泉', '原', '魄'], difficulty: 3 },
    { id: 270, character: '百', hiddenWords: ['口', '白', '百'], distractors: ['白', '日', '目', '田', '由', '甲', '申', '自', '宿', '佰', '陌', '佰'], difficulty: 3 },
    { id: 271, character: '自', hiddenWords: ['口', '目', '自'], distractors: ['白', '百', '日', '田', '由', '甲', '申', '臭', '鼻', '息', '咱', '泊'], difficulty: 3 },
    { id: 272, character: '臭', hiddenWords: ['口', '目', '自', '犬', '大', '人', '臭'], distractors: ['白', '百', '日', '田', '由', '臭', '鼻', '息', '嗅', '糗', '溴'], difficulty: 3 },
    { id: 273, character: '鼻', hiddenWords: ['口', '目', '自', '田', '鼻'], distractors: ['白', '百', '日', '由', '甲', '申', '自', '臭', '息', '劓', '鼾', '嚏'], difficulty: 3 },
    { id: 274, character: '息', hiddenWords: ['口', '目', '自', '心', '息'], distractors: ['白', '百', '日', '田', '由', '自', '臭', '鼻', '媳', '熄', '蟋', '螅'], difficulty: 3 },
    { id: 275, character: '由', hiddenWords: ['口', '由'], distractors: ['日', '目', '田', '甲', '申', '白', '百', '自', '抽', '油', '袖', '廟'], difficulty: 3 },
    { id: 276, character: '甲', hiddenWords: ['口', '甲'], distractors: ['日', '目', '田', '由', '申', '白', '百', '自', '押', '鴨', '胛', '閘'], difficulty: 3 },
    { id: 277, character: '申', hiddenWords: ['田', '口', '申'], distractors: ['日', '目', '由', '甲', '白', '百', '自', '神', '紳', '審', '伸'], difficulty: 3 },
    { id: 278, character: '電', hiddenWords: ['雨', '田', '口', '申', '電'], distractors: ['雷', '雹', '霜', '雪', '震', '霓', '霎', '霍', '霑', '靂', '霾', '霪'], difficulty: 3 },
    { id: 279, character: '雷', hiddenWords: ['雨', '田', '口', '雷'], distractors: ['電', '雹', '霜', '雪', '震', '霓', '霎', '霍', '蕾', '擂', '鐳', '儡'], difficulty: 3 },
    { id: 280, character: '雪', hiddenWords: ['雨', '雪'], distractors: ['電', '雷', '雹', '霜', '震', '霓', '霎', '霍', '鱈', '檽', '霽', '霾'], difficulty: 3 },
    { id: 281, character: '囈', hiddenWords: ['口', '言', '執', '丸', '囈'], distractors: ['藝', '褻', '熱', '勢', '墊', '摯', '贄', '鷙', '蓺', '塾', '縶', '熱'], difficulty: 3 },
    { id: 282, character: '藝', hiddenWords: ['草', '執', '丸', '雲', '藝'], distractors: ['囈', '褻', '熱', '勢', '墊', '摯', '贄', '鷙', '蓺', '塾', '縶', '熱'], difficulty: 3 },
    { id: 283, character: '熱', hiddenWords: ['執', '丸', '火', '熱'], distractors: ['囈', '藝', '褻', '勢', '墊', '摯', '贄', '鷙', '蓺', '塾', '縶', '熟'], difficulty: 3 },
    { id: 284, character: '勢', hiddenWords: ['執', '丸', '力', '勢'], distractors: ['囈', '藝', '褻', '熱', '墊', '摯', '贄', '鷙', '蓺', '塾', '縶', '熱'], difficulty: 3 },
    { id: 285, character: '墊', hiddenWords: ['執', '丸', '土', '墊'], distractors: ['囈', '藝', '褻', '熱', '勢', '摯', '贄', '鷙', '蓺', '塾', '縶', '熱'], difficulty: 3 },
    { id: 286, character: '摯', hiddenWords: ['執', '丸', '手', '摯'], distractors: ['囈', '藝', '褻', '熱', '勢', '墊', '贄', '鷙', '蓺', '塾', '縶', '熱'], difficulty: 3 },
    { id: 287, character: '熟', hiddenWords: ['享', '口', '火', '熟'], distractors: ['熱', '熟', '熟', '塾', '孰', '熟', '孰', '塾', '孰', '塾', '孰', '塾'], difficulty: 3 },
    { id: 288, character: '塾', hiddenWords: ['享', '口', '土', '塾'], distractors: ['熱', '熟', '熟', '熟', '孰', '熟', '孰', '熟', '孰', '熟', '孰', '熟'], difficulty: 3 },
    { id: 289, character: '膏', hiddenWords: ['高', '口', '月', '膏'], distractors: ['亮', '亭', '毫', '豪', '稿', '槁', '篙', '鎬', '犒', '膏', '膏', '膏'], difficulty: 3 },
    { id: 290, character: '高', hiddenWords: ['口', '高'], distractors: ['亮', '亭', '毫', '豪', '稿', '槁', '篙', '鎬', '犒', '膏', '高', '高'], difficulty: 3 },
    { id: 291, character: '亮', hiddenWords: ['口', '儿', '亮'], distractors: ['高', '亭', '毫', '豪', '稿', '槁', '篙', '鎬', '涼', '諒', '椋', '踉'], difficulty: 3 },
    { id: 292, character: '亭', hiddenWords: ['口', '丁', '亭'], distractors: ['高', '亮', '毫', '豪', '稿', '槁', '篙', '鎬', '停', '婷', '霆', '亭'], difficulty: 3 },
    { id: 293, character: '毫', hiddenWords: ['口', '毛', '毫'], distractors: ['高', '亮', '亭', '豪', '稿', '槁', '篙', '鎬', '氂', '旄', '麾', '髦'], difficulty: 3 },
    { id: 294, character: '豪', hiddenWords: ['口', '豕', '豪'], distractors: ['高', '亮', '亭', '毫', '稿', '槁', '篙', '鎬', '濠', '壕', '嚎', '蠔'], difficulty: 3 },
    { id: 295, character: '囊', hiddenWords: ['口', '襄', '囊'], distractors: ['囔', '攮', '曩', '纕', '驤', '鑲', '饟', '蘘', '襠', '稂', '莨', '鋃'], difficulty: 3 },
    { id: 296, character: '碧', hiddenWords: ['王', '白', '石', '口', '碧'], distractors: ['岩', '研', '破', '瑞', '玻', '璃', '璨', '粕', '泉', '原', '斑', '玛'], difficulty: 3 },
    { id: 297, character: '驾', hiddenWords: ['加', '力', '口', '马', '驾'], distractors: ['驾', '骂', '架', '枷', '茄', '驼', '驴', '驶', '驻', '驹', '骀', '驽'], difficulty: 3 },
    { id: 298, character: '骂', hiddenWords: ['口', '马', '骂'], distractors: ['驾', '架', '枷', '驼', '驴', '驶', '驻', '驹', '嚣', '哭', '器', '噪'], difficulty: 3 },
    { id: 299, character: '桑', hiddenWords: ['又', '木', '人', '桑'], distractors: ['集', '柔', '某', '架', '染', '条', '枭', '桒', '双', '叕', '圣', '仅'], difficulty: 3 },
    { id: 300, character: '染', hiddenWords: ['水', '九', '木', '人', '染'], distractors: ['桑', '柒', '梁', '柔', '某', '柴', '案', '剁', '杂', '烫', '浆', '桨'], difficulty: 3 },

    // ========== 難度3-4：中難度跨越（301-350關：形近字拆解，干擾項極強） ==========
    { id: 301, character: '憋', hiddenWords: ['币', '攵', '心', '憋'], distractors: ['憋', '蹩', '瞥', '弊', '蔽', '憋', '憋', '怒', '怨', '愁', '憨', '憩'], difficulty: 3 },
    { id: 302, character: '蹩', hiddenWords: ['币', '攵', '足', '口', '蹩'], distractors: ['憋', '瞥', '弊', '蔽', '蹩', '跛', '跌', '跑', '跳', '路', '跟', '蹄'], difficulty: 3 },
    { id: 303, character: '瞥', hiddenWords: ['币', '攵', '目', '口', '瞥'], distractors: ['憋', '蹩', '弊', '蔽', '瞥', '看', '盯', '眇', '盼', '睜', '眩', '瞧'], difficulty: 3 },
    { id: 304, character: '塵', hiddenWords: ['鹿', '广', '比', '匕', '土', '塵'], distractors: ['塵', '鏖', '麈', '麋', '麒', '麟', '堂', '坐', '壁', '墨', '墾', '墊'], difficulty: 4 },
    { id: 305, character: '鏖', hiddenWords: ['鹿', '广', '比', '匕', '金', '鏖'], distractors: ['塵', '麈', '麋', '麒', '麟', '鏖', '鑑', '釜', '鑿', '鐵', '鋼', '銅'], difficulty: 4 },
    { id: 306, character: '磨', hiddenWords: ['广', '木', '人', '林', '石', '口', '磨'], distractors: ['魔', '靡', '蘑', '摩', '磨', '研', '破', '碧', '砍', '砂', '砌', '磊'], difficulty: 3 },
    { id: 307, character: '魔', hiddenWords: ['广', '木', '人', '林', '鬼', '口', '魔'], distractors: ['磨', '靡', '蘑', '摩', '魔', '魅', '魁', '魃', '魄', '魂', '魎', '魏'], difficulty: 4 },
    { id: 308, character: '靡', hiddenWords: ['广', '木', '人', '林', '非', '靡'], distractors: ['磨', '魔', '蘑', '摩', '靡', '排', '靠', '悲', '扉', '罪', '輩', '斐'], difficulty: 4 },
    { id: 309, character: '蘑', hiddenWords: ['草', '广', '木', '人', '林', '石', '口', '磨', '蘑'], distractors: ['魔', '靡', '摩', '磨', '蘸', '薪', '蘆', '蘇', '蘢', '藺', '蘄', '藻'], difficulty: 4 },
    { id: 310, character: '摩', hiddenWords: ['广', '木', '人', '林', '手', '摩'], distractors: ['磨', '魔', '靡', '蘑', '摩', '擦', '摸', '攀', '擎', '摹', '掰', '摯'], difficulty: 3 },
    { id: 311, character: '岩', hiddenWords: ['山', '石', '口', '岩'], distractors: ['岸', '炭', '宕', '礦', '研', '碧', '砸', '砂', '砌', '磊', '礪', '磯'], difficulty: 3 },
    { id: 312, character: '炭', hiddenWords: ['山', '火', '人', '炭'], distractors: ['岩', '岸', '宕', '灰', '滅', '災', '靈', '灶', '炒', '炕', '烘', '烤'], difficulty: 3 },
    { id: 313, character: '岸', hiddenWords: ['山', '干', '厂', '岸'], distractors: ['岩', '炭', '宕', '悍', '焊', '捍', '憨', '罕', '旱', '笨', '竿', '算'], difficulty: 3 },
    { id: 314, character: '祟', hiddenWords: ['出', '山', '示', '祟'], distractors: ['崇', '歲', '祟', '祭', '禁', '梵', '察', '擦', '祟', '宗', '崇', '祟'], difficulty: 3 },
    { id: 315, character: '崇', hiddenWords: ['山', '宗', '崇'], distractors: ['祟', '歲', '崇', '崇', '祭', '禁', '梵', '察', '擦', '祟', '宗', '祟'], difficulty: 3 },
    { id: 316, character: '歲', hiddenWords: ['山', '夕', '歲'], distractors: ['祟', '崇', '歲', '歲', '祭', '禁', '梵', '察', '擦', '祟', '宗', '祟'], difficulty: 4 },
    { id: 317, character: '卡', hiddenWords: ['上', '下', '卡'], distractors: ['占', '步', '盧', '卓', '乒', '乓', '卜', '卞', '入', '引', '卡', '卡'], difficulty: 3 },
    { id: 318, character: '步', hiddenWords: ['止', '步'], distractors: ['卡', '涉', '頻', '肯', '武', '歧', '歲', '歪', '奔', '走', '跑', '跳'], difficulty: 3 },
    { id: 319, character: '歪', hiddenWords: ['不', '正', '止', '歪'], distractors: ['否', '還', '壞', '杯', '環', '杯', '步', '卡', '肯', '武', '歧', '歲'], difficulty: 3 },
    { id: 320, character: '肯', hiddenWords: ['止', '月', '肯'], distractors: ['步', '武', '歧', '歲', '歪', '骨', '胃', '背', '腎', '育', '肴', '胥'], difficulty: 3 },
    { id: 321, character: '名', hiddenWords: ['夕', '口', '名'], distractors: ['各', '各', '各', '各', '各', '各', '明', '銘', '茗', '酩', '洺', '胳'], difficulty: 3 },
    { id: 322, character: '各', hiddenWords: ['口', '各'], distractors: ['名', '名', '名', '名', '名', '名', '格', '客', '略', '烙', '駱', '洛'], difficulty: 3 },
    { id: 323, character: '路', hiddenWords: ['足', '口', '各', '路'], distractors: ['露', '賂', '璐', '潞', '鷺', '璐', '踏', '踊', '跑', '跳', '距', '跪'], difficulty: 3 },
    { id: 324, character: '賂', hiddenWords: ['貝', '口', '各', '賂'], distractors: ['路', '露', '璐', '潞', '鷺', '賂', '財', '貧', '貪', '責', '賢', '費'], difficulty: 3 },
    { id: 325, character: '骨', hiddenWords: ['口', '月', '骨'], distractors: ['滑', '骰', '骷', '髏', '骼', '髓', '肯', '胃', '背', '腎', '育', '肴'], difficulty: 3 },
    { id: 326, character: '滑', hiddenWords: ['水', '口', '月', '骨', '滑'], distractors: ['骰', '骷', '髏', '骼', '髓', '骨', '骨', '骨', '骨', '骨', '骨', '骨'], difficulty: 3 },
    { id: 327, character: '隋', hiddenWords: ['月', '口', '隋'], distractors: ['隨', '髓', '惰', '橢', '墮', '隨', '隨', '隨', '隨', '隨', '隨', '隨'], difficulty: 3 },
    { id: 328, character: '隨', hiddenWords: ['月', '口', '隋', '隨'], distractors: ['隋', '髓', '惰', '橢', '墮', '隨', '隨', '隨', '隨', '隨', '隨', '隨'], difficulty: 4 },
    { id: 329, character: '髓', hiddenWords: ['骨', '口', '月', '隋', '髓'], distractors: ['隋', '隨', '惰', '橢', '墮', '髓', '髓', '髓', '髓', '髓', '髓', '髓'], difficulty: 4 },
    { id: 330, character: '牆', hiddenWords: ['土', '嗇', '土', '口', '牆'], distractors: ['薔', '嬙', '檣', '檣', '牆', '牆', '牆', '牆', '牆', '牆', '牆', '牆'], difficulty: 4 },
    { id: 331, character: '薔', hiddenWords: ['草', '嗇', '土', '口', '薔'], distractors: ['牆', '嬙', '檣', '檣', '薔', '薔', '薔', '薔', '薔', '薔', '薔', '薔'], difficulty: 4 },
    { id: 332, character: '牆', hiddenWords: ['木', '嗇', '土', '口', '牆'], distractors: ['牆', '薔', '嬙', '檣', '牆', '牆', '牆', '牆', '牆', '牆', '牆', '牆'], difficulty: 4 },
    { id: 333, character: '賈', hiddenWords: ['西', '口', '貝', '賈'], distractors: ['要', '栗', '覆', '買', '賣', '讀', '續', '贖', '賡', '賻', '贅', '賾'], difficulty: 3 },
    { id: 334, character: '賡', hiddenWords: ['广', '口', '貝', '賡'], distractors: ['賈', '賡', '賡', '康', '唐', '庸', '賻', '贅', '賾', '賡', '賡', '賡'], difficulty: 4 },
    { id: 335, character: '贅', hiddenWords: ['五', '貝', '贅'], distractors: ['賈', '賡', '賻', '贅', '賾', '贅', '敖', '贅', '贅', '贅', '贅', '贅'], difficulty: 4 },
    { id: 336, character: '熏', hiddenWords: ['千', '口', '黑', '熏'], distractors: ['黑', '熏', '熏', '熏', '熏', '熏', '墨', '默', '黛', '黜', '黝', '點'], difficulty: 4 },
    { id: 337, character: '黑', hiddenWords: ['口', '土', '黑'], distractors: ['熏', '墨', '默', '黛', '黜', '黝', '點', '黠', '黥', '黨', '黯', '霉'], difficulty: 3 },
    { id: 338, character: '墨', hiddenWords: ['口', '土', '黑', '墨'], distractors: ['熏', '黑', '默', '黛', '黜', '黝', '點', '黠', '黥', '黨', '黯', '塵'], difficulty: 4 },
    { id: 339, character: '默', hiddenWords: ['口', '土', '黑', '犬', '大', '人', '默'], distractors: ['熏', '黑', '墨', '黛', '黜', '黝', '點', '黠', '黥', '黨', '黯', '默'], difficulty: 4 },
    { id: 340, character: '點', hiddenWords: ['口', '土', '黑', '口', '占', '卜', '點'], distractors: ['熏', '黑', '墨', '默', '黛', '黜', '黝', '黠', '黥', '黨', '黯', '點'], difficulty: 4 },
    { id: 341, character: '黨', hiddenWords: ['口', '土', '黑', '儿', '黨'], distractors: ['熏', '黑', '墨', '默', '黛', '黜', '黝', '點', '黠', '黥', '黯', '堂'], difficulty: 4 },
    { id: 342, character: '堂', hiddenWords: ['土', '口', '堂'], distractors: ['黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 3 },
    { id: 343, character: '常', hiddenWords: ['口', '巾', '常'], distractors: ['堂', '黨', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 3 },
    { id: 344, character: '賞', hiddenWords: ['口', '貝', '賞'], distractors: ['堂', '黨', '常', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 3 },
    { id: 345, character: '掌', hiddenWords: ['口', '手', '掌'], distractors: ['堂', '黨', '常', '賞', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 3 },
    { id: 346, character: '裳', hiddenWords: ['口', '衣', '裳'], distractors: ['堂', '黨', '常', '賞', '掌', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 4 },
    { id: 347, character: '躺', hiddenWords: ['身', '口', '躺'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 4 },
    { id: 348, character: '棠', hiddenWords: ['口', '木', '人', '棠'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 4 },
    { id: 349, character: '糖', hiddenWords: ['米', '木', '人', '口', '糖'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '膛'], difficulty: 4 },
    { id: 350, character: '膛', hiddenWords: ['月', '口', '膛'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖'], difficulty: 4 },

    // ========== 難度4：核心高階（351-400關：結構更復雜，多重包圍與堆疊字） ==========
    { id: 351, character: '晶', hiddenWords: ['日', '口', '晶'], distractors: ['昌', '明', '晃', '昆', '森', '淼', '焱', '磊', '垚', '掾', '品', '矗'], difficulty: 3 },
    { id: 352, character: '品', hiddenWords: ['口', '品'], distractors: ['晶', '昌', '明', '森', '淼', '焱', '磊', '垚', '矗', '臨', '操', '噪'], difficulty: 3 },
    { id: 353, character: '磊', hiddenWords: ['石', '口', '磊'], distractors: ['晶', '品', '昌', '森', '淼', '焱', '垚', '矗', '研', '破', '碧', '硬'], difficulty: 3 },
    { id: 354, character: '淼', hiddenWords: ['水', '淼'], distractors: ['晶', '品', '昌', '森', '焱', '磊', '垚', '矗', '渺', '渺', '漂', '流'], difficulty: 3 },
    { id: 355, character: '焱', hiddenWords: ['火', '人', '焱'], distractors: ['晶', '品', '昌', '森', '淼', '磊', '垚', '矗', '滅', '災', '靈', '炎'], difficulty: 4 },
    { id: 356, character: '垚', hiddenWords: ['土', '垚'], distractors: ['晶', '品', '昌', '森', '淼', '焱', '磊', '矗', '堂', '坐', '壁', '墨'], difficulty: 4 },
    { id: 357, character: '矗', hiddenWords: ['十', '立', '目', '口', '直', '矗'], distractors: ['晶', '品', '昌', '森', '淼', '焱', '磊', '垚', '直', '置', '植', '殖'], difficulty: 4 },
    { id: 358, character: '直', hiddenWords: ['十', '立', '目', '口', '直'], distractors: ['置', '植', '殖', '值', '職', '矗', '德', '聽', '盾', '省', '看', '眉'], difficulty: 3 },
    { id: 359, character: '置', hiddenWords: ['十', '立', '目', '口', '直', '置'], distractors: ['直', '植', '殖', '值', '職', '矗', '德', '聽', '罰', '罪', '署', '罩'], difficulty: 4 },
    { id: 360, character: '植', hiddenWords: ['木', '人', '十', '立', '目', '口', '直', '植'], distractors: ['直', '置', '殖', '值', '職', '矗', '德', '聽', '株', '根', '林', '森'], difficulty: 4 },
    { id: 361, character: '殖', hiddenWords: ['十', '立', '目', '口', '直', '殖'], distractors: ['直', '置', '植', '值', '職', '矗', '德', '聽', '死', '殃', '殮', '殯'], difficulty: 4 },
    { id: 362, character: '值', hiddenWords: ['人', '十', '立', '目', '口', '直', '值'], distractors: ['直', '置', '植', '殖', '職', '矗', '德', '聽', '估', '仲', '伸', '保'], difficulty: 4 },
    { id: 363, character: '職', hiddenWords: ['耳', '十', '立', '目', '口', '直', '職'], distractors: ['直', '置', '植', '殖', '值', '矗', '德', '聽', '聘', '耽', '聊', '聯'], difficulty: 4 },
    { id: 364, character: '德', hiddenWords: ['十', '目', '口', '心', '直', '德'], distractors: ['直', '聽', '職', '德', '聽', '聰', '穗', '聽', '聽', '聽', '聽', '聽'], difficulty: 4 },
    { id: 365, character: '聽', hiddenWords: ['耳', '十', '目', '口', '心', '直', '聽'], distractors: ['直', '德', '職', '聽', '聰', '穗', '聽', '聽', '聽', '聽', '聽', '聽'], difficulty: 4 },
    { id: 366, character: '聰', hiddenWords: ['耳', '口', '心', '聰'], distractors: ['聽', '德', '職', '聰', '總', '腮', '鰓', '驄', '怱', '匆', '聰', '聰'], difficulty: 4 },
    { id: 367, character: '總', hiddenWords: ['糸', '口', '心', '總'], distractors: ['聽', '德', '職', '聰', '總', '腮', '鰓', '驄', '怱', '匆', '總', '總'], difficulty: 4 },
    { id: 368, character: '腮', hiddenWords: ['月', '田', '口', '心', '腮'], distractors: ['聽', '德', '職', '聰', '總', '鰓', '驄', '怱', '匆', '腮', '腮', '腮'], difficulty: 4 },
    { id: 369, character: '鰓', hiddenWords: ['魚', '田', '口', '心', '鰓'], distractors: ['聽', '德', '職', '聰', '總', '腮', '驄', '怱', '匆', '鰓', '鰓', '鰓'], difficulty: 4 },
    { id: 370, character: '驄', hiddenWords: ['馬', '口', '心', '驄'], distractors: ['聽', '德', '職', '聰', '總', '腮', '鰓', '怱', '匆', '驄', '驄', '驄'], difficulty: 4 },
    { id: 371, character: '魚', hiddenWords: ['田', '口', '魚'], distractors: ['漁', '鮮', '鯉', '鯽', '鯨', '鯊', '鮑', '鰻', '鰾', '鱘', '鱔', '鱉'], difficulty: 3 },
    { id: 372, character: '漁', hiddenWords: ['水', '田', '口', '魚', '漁'], distractors: ['魚', '鮮', '鯉', '鯽', '鯨', '鯊', '鮑', '鰻', '鰾', '鱘', '鱔', '鱉'], difficulty: 4 },
    { id: 373, character: '鮮', hiddenWords: ['田', '口', '魚', '羊', '鮮'], distractors: ['魚', '漁', '鯉', '鯽', '鯨', '鯊', '鮑', '鰻', '差', '羞', '詳', '羔'], difficulty: 4 },
    { id: 374, character: '鯉', hiddenWords: ['田', '口', '魚', '里', '土', '鯉'], distractors: ['魚', '漁', '鮮', '鯽', '鯨', '鯊', '鮑', '鰻', '理', '埋', '量', '童'], difficulty: 4 },
    { id: 375, character: '鯽', hiddenWords: ['田', '口', '魚', '鯽'], distractors: ['魚', '漁', '鮮', '鯉', '鯨', '鯊', '鮑', '鰻', '即', '既', '唧', '節'], difficulty: 4 },
    { id: 376, character: '鯨', hiddenWords: ['田', '口', '魚', '京', '鯨'], distractors: ['魚', '漁', '鮮', '鯉', '鯽', '鯊', '鮑', '鰻', '涼', '諒', '景', '就'], difficulty: 4 },
    { id: 377, character: '鯊', hiddenWords: ['田', '口', '魚', '水', '沙', '鯊'], distractors: ['魚', '漁', '鮮', '鯉', '鯽', '鯨', '鮑', '鰻', '沙', '紗', '砂', '莎'], difficulty: 4 },
    { id: 378, character: '鮑', hiddenWords: ['田', '口', '魚', '包', '鮑'], distractors: ['魚', '漁', '鮮', '鯉', '鯽', '鯨', '鯊', '鰻', '飽', '抱', '胞', '跑'], difficulty: 4 },
    { id: 379, character: '鰻', hiddenWords: ['田', '口', '魚', '日', '四', '曼', '鰻'], distractors: ['魚', '漁', '鮮', '鯉', '鯽', '鯨', '鯊', '鮑', '慢', '漫', '饅', '謾'], difficulty: 4 },
    { id: 380, character: '曼', hiddenWords: ['日', '口', '四', '曼'], distractors: ['慢', '漫', '饅', '謾', '蔓', '幔', '鏝', '鰻', '最', '冒', '冕', '勗'], difficulty: 3 },
    { id: 381, character: '慢', hiddenWords: ['心', '日', '口', '四', '曼', '慢'], distractors: ['曼', '漫', '饅', '謾', '蔓', '幔', '鏝', '鰻', '快', '愣', '慌', '愧'], difficulty: 4 },
    { id: 382, character: '漫', hiddenWords: ['水', '日', '口', '四', '曼', '漫'], distractors: ['曼', '慢', '饅', '謾', '蔓', '幔', '鏝', '鰻', '流', '浪', '漂', '泄'], difficulty: 4 },
    { id: 383, character: '饅', hiddenWords: ['食', '日', '口', '四', '曼', '饅'], distractors: ['曼', '慢', '漫', '謾', '蔓', '幔', '鏝', '鰻', '飯', '餅', '餃', '飽'], difficulty: 4 },
    { id: 384, character: '謾', hiddenWords: ['言', '日', '口', '四', '曼', '謾'], distractors: ['曼', '慢', '漫', '饅', '蔓', '幔', '鏝', '鰻', '說', '話', '語', '誰'], difficulty: 4 },
    { id: 385, character: '蔓', hiddenWords: ['草', '日', '口', '四', '曼', '蔓'], distractors: ['曼', '慢', '漫', '饅', '謾', '幔', '鏝', '鰻', '花', '菜', '蘆', '蘇'], difficulty: 4 },
    { id: 386, character: '最', hiddenWords: ['日', '口', '耳', '又', '取', '最'], distractors: ['曼', '冒', '冕', '勗', '聚', '趣', '娶', '職', '聰', '耿', '恥', '聊'], difficulty: 3 },
    { id: 387, character: '取', hiddenWords: ['耳', '又', '取'], distractors: ['最', '聚', '趣', '娶', '職', '聰', '耿', '恥', '聊', '聯', '聘', '耽'], difficulty: 3 },
    { id: 388, character: '聚', hiddenWords: ['耳', '又', '聚'], distractors: ['最', '取', '趣', '娶', '職', '聰', '驟', '驟', '叢', '眾', '從', '人'], difficulty: 4 },
    { id: 389, character: '趣', hiddenWords: ['土', '走', '耳', '又', '取', '趣'], distractors: ['最', '取', '聚', '娶', '職', '趨', '趙', '赶', '超', '越', '起', '徒'], difficulty: 4 },
    { id: 390, character: '娶', hiddenWords: ['耳', '又', '取', '女', '娶'], distractors: ['最', '取', '聚', '趣', '姿', '妥', '姜', '委', '婁', '娛', '姻', '媒'], difficulty: 4 },
    { id: 391, character: '罷', hiddenWords: ['四', '去', '土', '罷'], distractors: ['擺', '擺', '擺', '羆', '羆', '疲', '披', '被', '破', '波', '玻', '坡'], difficulty: 4 },
    { id: 392, character: '擺', hiddenWords: ['手', '四', '去', '土', '罷', '擺'], distractors: ['罷', '羆', '疲', '披', '被', '破', '波', '推', '拉', '提', '搬', '擦'], difficulty: 4 },
    { id: 393, character: '羆', hiddenWords: ['四', '去', '土', '火', '罷', '羆'], distractors: ['罷', '擺', '熊', '熙', '熟', '熱', '羔', '熬', '蒸', '烹', '煎', '烈'], difficulty: 4 },
    { id: 394, character: '熊', hiddenWords: ['匕', '月', '火', '熊'], distractors: ['羆', '熙', '熟', '熱', '羔', '熬', '蒸', '烹', '煎', '烈', '能', '態'], difficulty: 4 },
    { id: 395, character: '能', hiddenWords: ['匕', '月', '能'], distractors: ['熊', '態', '罷', '擺', '罷', '罷', '罷', '罷', '罷', '罷', '罷', '罷'], difficulty: 3 },
    { id: 396, character: '態', hiddenWords: ['匕', '月', '心', '能', '態'], distractors: ['熊', '能', '態', '怒', '怨', '愁', '憨', '憩', '憊', '懣', '憑', '懇'], difficulty: 4 },
    { id: 397, character: '憊', hiddenWords: ['广', '用', '心', '憊'], distractors: ['態', '能', '熊', '怒', '怨', '愁', '憨', '憩', '懣', '憑', '懇', '懸'], difficulty: 4 },
    { id: 398, character: '憑', hiddenWords: ['几', '馬', '心', '憑'], distractors: ['態', '能', '熊', '怒', '怨', '愁', '憨', '憩', '憊', '懣', '懇', '懸'], difficulty: 4 },
    { id: 399, character: '懇', hiddenWords: ['口', '疋', '心', '懇'], distractors: ['態', '能', '熊', '怒', '怨', '愁', '憨', '憩', '憊', '懣', '憑', '懸'], difficulty: 4 },
    { id: 400, character: '懸', hiddenWords: ['县', '目', '口', '心', '懸'], distractors: ['態', '能', '熊', '怒', '怨', '愁', '憨', '憩', '憊', '懣', '憑', '懇'], difficulty: 4 },

    // ========== 難度4：核心高階（401-450關：覆雜形聲與堆疊合體字，極考眼力） ==========
    { id: 401, character: '赢', hiddenWords: ['亡', '口', '月', '贝', '凡', '赢'], distractors: ['羸', '蠃', '嬴', '瀛', '籯', '慷', '膏', '亮', '豪', '毫', '亭', '高'], difficulty: 4 },
    { id: 402, character: '嬴', hiddenWords: ['亡', '口', '月', '女', '凡', '嬴'], distractors: ['赢', '羸', '蠃', '瀛', '籯', '姿', '妥', '姜', '委', '娄', '娱', '姻'], difficulty: 4 },
    { id: 403, character: '外', hiddenWords: ['夕', '卜', '外'], distractors: ['处', '名', '各', '咎', '卧', '扑', '补', '卦', '卧', '舛', '桀', '怨'], difficulty: 3 },
    { id: 404, character: '处', hiddenWords: ['夕', '卜', '处'], distractors: ['外', '名', '各', '咎', '卧', '扑', '补', '卦', '咎', '咎', '舅', '咎'], difficulty: 3 },
    { id: 405, character: '咎', hiddenWords: ['口', '各', '咎'], distractors: ['名', '处', '外', '卜', '卧', '扑', '补', '卦', '舅', '晷', '咎', '咎'], difficulty: 3 },
    { id: 406, character: '韶', hiddenWords: ['立', '日', '口', '音', '刀', '召', '韶'], distractors: ['章', '意', '竟', '招', '昭', '沼', '迢', '韶', '韶', '韶', '韶', '韶'], difficulty: 4 },
    { id: 407, character: '意', hiddenWords: ['立', '日', '口', '心', '音', '意'], distractors: ['章', '竟', '韶', '億', '臆', '薏', '怱', '匆', '總', '聰', '腮', '鰓'], difficulty: 4 },
    { id: 408, character: '霸', hiddenWords: ['雨', '革', '月', '霸'], distractors: ['雷', '雹', '霜', '雪', '震', '霓', '霎', '霍', '露', '霧', '靂', '霾'], difficulty: 4 },
    { id: 409, character: '露', hiddenWords: ['雨', '路', '足', '各', '口', '露'], distractors: ['雷', '雹', '霜', '雪', '震', '霓', '霎', '霍', '霸', '霧', '靂', '霾'], difficulty: 4 },
    { id: 410, character: '霧', hiddenWords: ['雨', '務', '力', '務', '霧'], distractors: ['雷', '雹', '霜', '雪', '震', '霓', '霎', '霍', '霸', '露', '靂', '霾'], difficulty: 4 },
    { id: 411, character: '靂', hiddenWords: ['雨', '歷', '厂', '靂'], distractors: ['雷', '雹', '霜', '雪', '震', '霓', '霎', '霍', '霸', '露', '霧', '霾'], difficulty: 4 },
    { id: 412, character: '霾', hiddenWords: ['雨', '埋', '土', '里', '田', '口', '霾'], distractors: ['雷', '雹', '霜', '雪', '震', '霓', '霎', '霍', '霸', '露', '霧', '靂'], difficulty: 4 },
    { id: 413, character: '裹', hiddenWords: ['衣', '果', '日', '口', '木', '人', '裹'], distractors: ['裸', '裏', '裏', '裏', '裏', '裏', '課', '棵', '顆', '裏', '裏', '裏'], difficulty: 4 },
    { id: 414, character: '裏', hiddenWords: ['衣', '里', '田', '口', '土', '裏'], distractors: ['裸', '裹', '裹', '裹', '裹', '裹', '理', '埋', '量', '童', '厘', '野'], difficulty: 4 },
    { id: 415, character: '襄', hiddenWords: ['口', '襄'], distractors: ['囊', '囔', '攮', '曩', '纕', '驤', '鑲', '饟', '蘘', '襠', '稂', '莨'], difficulty: 4 },
    { id: 416, character: '囊', hiddenWords: ['口', '襄', '囊'], distractors: ['襄', '囔', '攮', '曩', '纕', '驤', '鑲', '饟', '蘘', '襠', '稂', '莨'], difficulty: 4 },
    { id: 417, character: '攀', hiddenWords: ['木', '人', '林', '手', '攀'], distractors: ['樊', '攀', '攀', '攀', '攀', '攀', '擎', '摹', '掰', '手', '掌', '摯'], difficulty: 4 },
    { id: 418, character: '樊', hiddenWords: ['木', '人', '林', '樊'], distractors: ['攀', '樊', '樊', '樊', '樊', '樊', '郁', '礬', '蘩', '釩', '攀', '樊'], difficulty: 4 },
    { id: 419, character: '檠', hiddenWords: ['文', '口', '言', '木', '人', '檠'], distractors: ['擎', '黥', '擎', '擎', '警', '驚', '擎', '擎', '擎', '擎', '擎', '擎'], difficulty: 4 },
    { id: 420, character: '擎', hiddenWords: ['文', '口', '言', '手', '擎'], distractors: ['檠', '黥', '檠', '檠', '警', '驚', '檠', '檠', '檠', '檠', '檠', '檠'], difficulty: 4 },
    { id: 421, character: '黥', hiddenWords: ['文', '口', '言', '黑', '土', '黥'], distractors: ['檠', '擎', '檠', '檠', '警', '驚', '墨', '默', '黛', '黜', '黝', '點'], difficulty: 4 },
    { id: 422, character: '警', hiddenWords: ['文', '口', '言', '言', '警'], distractors: ['檠', '擎', '黥', '驚', '譬', '擎', '說', '話', '語', '誰', '諸', '謝'], difficulty: 4 },
    { id: 423, character: '驚', hiddenWords: ['文', '口', '言', '馬', '驚'], distractors: ['檠', '擎', '黥', '警', '譬', '擎', '闖', '駕', '罵', '駝', '驢', '駛'], difficulty: 4 },
    { id: 424, character: '譬', hiddenWords: ['口', '言', '譬'], distractors: ['檠', '擎', '黥', '警', '驚', '譬', '壁', '臂', '避', '僻', '癖', '璧'], difficulty: 4 },
    { id: 425, character: '壁', hiddenWords: ['土', '壁'], distractors: ['譬', '臂', '避', '僻', '癖', '璧', '堂', '坐', '聖', '墨', '墾', '墊'], difficulty: 4 },
    { id: 426, character: '臂', hiddenWords: ['月', '臂'], distractors: ['譬', '壁', '避', '僻', '癖', '璧', '骨', '胃', '背', '腎', '育', '肴'], difficulty: 4 },
    { id: 427, character: '避', hiddenWords: ['避'], distractors: ['譬', '壁', '臂', '僻', '癖', '璧', '透', '過', '逃', '迎', '追', '速'], difficulty: 4 },
    { id: 428, character: '瓣', hiddenWords: ['辛', '十', '口', '瓜', '瓣'], distractors: ['辨', '辯', '辦', '辭', '辟', '壁', '臂', '避', '幸', '梓', '辣', '辨'], difficulty: 4 },
    { id: 429, character: '辨', hiddenWords: ['辛', '十', '口', '辨'], distractors: ['瓣', '辯', '辦', '辭', '辟', '壁', '臂', '避', '幸', '梓', '辣', '瓣'], difficulty: 4 },
    { id: 430, character: '辯', hiddenWords: ['辛', '十', '口', '言', '辯'], distractors: ['瓣', '辨', '辦', '辭', '辟', '壁', '臂', '避', '說', '話', '語', '誰'], difficulty: 4 },
    { id: 431, character: '辦', hiddenWords: ['力', '辦'], distractors: ['瓣', '辨', '辯', '辭', '辟', '壁', '臂', '避', '男', '劣', '加', '功'], difficulty: 3 },
    { id: 432, character: '辭', hiddenWords: ['舌', '千', '口', '辛', '十', '口', '辭'], distractors: ['瓣', '辨', '辯', '辦', '辟', '壁', '臂', '避', '話', '甜', '刮', '敵'], difficulty: 4 },
    { id: 433, character: '解', hiddenWords: ['角', '刀', '牛', '解'], distractors: ['解', '懈', '蟹', '邂', '獬', '廨', '解', '解', '解', '解', '解', '解'], difficulty: 4 },
    { id: 434, character: '懈', hiddenWords: ['心', '角', '刀', '牛', '解', '懈'], distractors: ['解', '蟹', '邂', '獬', '廨', '解', '快', '愣', '慌', '愧', '懈', '懈'], difficulty: 4 },
    { id: 435, character: '蟹', hiddenWords: ['角', '刀', '牛', '解', '虫', '蟹'], distractors: ['解', '懈', '邂', '獬', '廨', '解', '茧', '蛮', '蛰', '蛾', '蜂', '蜘'], difficulty: 4 },
    { id: 436, character: '邂', hiddenWords: ['角', '刀', '牛', '解', '邂'], distractors: ['解', '懈', '蟹', '獬', '廨', '解', '透', '過', '逃', '迎', '追', '速'], difficulty: 4 },
    { id: 437, character: '贅', hiddenWords: ['五', '貝', '贅'], distractors: ['賈', '賡', '賻', '贅', '賾', '贅', '敖', '贅', '贅', '贅', '贅', '贅'], difficulty: 4 },
    { id: 438, character: '賾', hiddenWords: ['巨', '臣', '貝', '賾'], distractors: ['賈', '賡', '賻', '贅', '贅', '頤', '姬', '臨', '監', '賢', '覽', '藍'], difficulty: 4 },
    { id: 439, character: '頤', hiddenWords: ['巨', '臣', '頁', '口', '貝', '頤'], distractors: ['賈', '賡', '賻', '贅', '賾', '姬', '臨', '監', '賢', '覽', '頂', '項'], difficulty: 4 },
    { id: 440, character: '臨', hiddenWords: ['臣', '口', '臨'], distractors: ['巨', '監', '賢', '覽', '藍', '籃', '艦', '舟', '般', '船', '航', '盤'], difficulty: 4 },
    { id: 441, character: '監', hiddenWords: ['臣', '口', '皿', '監'], distractors: ['巨', '臨', '賢', '藍', '籃', '艦', '舟', '般', '船', '航', '盤', '皿'], difficulty: 4 },
    { id: 442, character: '覽', hiddenWords: ['臣', '口', '見', '儿', '覽'], distractors: ['巨', '臨', '監', '藍', '籃', '艦', '舟', '般', '船', '航', '盤', '見'], difficulty: 4 },
    { id: 443, character: '藍', hiddenWords: ['草', '臣', '口', '皿', '監', '藍'], distractors: ['巨', '臨', '監', '覽', '籃', '艦', '舟', '般', '船', '航', '盤', '花'], difficulty: 4 },
    { id: 444, character: '籃', hiddenWords: ['竹', '臣', '口', '皿', '監', '籃'], distractors: ['巨', '臨', '監', '覽', '藍', '艦', '舟', '般', '船', '航', '盤', '竿'], difficulty: 4 },
    { id: 445, character: '艦', hiddenWords: ['舟', '臣', '口', '皿', '監', '艦'], distractors: ['巨', '臨', '監', '覽', '藍', '籃', '舟', '般', '船', '航', '盤', '丹'], difficulty: 4 },
    { id: 446, character: '盤', hiddenWords: ['舟', '般', '皿', '盤'], distractors: ['丹', '船', '航', '監', '盟', '盛', '盜', '益', '盒', '盔', '盞', '血'], difficulty: 4 },
    { id: 447, character: '盟', hiddenWords: ['日', '口', '月', '皿', '明', '盟'], distractors: ['盜', '盛', '益', '盒', '盔', '盞', '盤', '監', '朋', '晶', '晃', '昆'], difficulty: 4 },
    { id: 448, character: '盛', hiddenWords: ['皿', '盛'], distractors: ['盜', '盟', '益', '盒', '盔', '盞', '盤', '監', '成', '城', '誠', '威'], difficulty: 3 },
    { id: 449, character: '誠', hiddenWords: ['言', '誠'], distractors: ['成', '城', '盛', '威', '咸', '感', '憾', '喊', '減', '喊', '說', '話'], difficulty: 3 },
    { id: 450, character: '感', hiddenWords: ['咸', '口', '心', '感'], distractors: ['成', '城', '盛', '威', '誠', '憾', '喊', '減', '喊', '怒', '怨', '愁'], difficulty: 4 },

    // ========== 難度4進階：高密度結構（451-500關：四重包圍、生僻部件與多干擾項複合） ==========
    { id: 451, character: '憾', hiddenWords: ['心', '咸', '口', '憾'], distractors: ['成', '城', '盛', '威', '誠', '感', '喊', '減', '喊', '快', '愣', '慌'], difficulty: 4 },
    { id: 452, character: '喊', hiddenWords: ['口', '咸', '口', '喊'], distractors: ['成', '城', '盛', '威', '誠', '感', '憾', '減', '噪', '哭', '器', '品'], difficulty: 4 },
    { id: 453, character: '減', hiddenWords: ['水', '咸', '口', '減'], distractors: ['成', '城', '盛', '威', '誠', '感', '憾', '喊', '流', '浪', '漂', '泄'], difficulty: 4 },
    { id: 454, character: '意', hiddenWords: ['立', '日', '口', '心', '音', '意'], distractors: ['章', '竟', '韶', '億', '臆', '薏', '怱', '匆', '總', '聰', '腮', '鰓'], difficulty: 4 },
    { id: 455, character: '億', hiddenWords: ['人', '立', '日', '口', '音', '意', '億'], distractors: ['章', '竟', '韶', '意', '臆', '薏', '估', '仲', '伸', '保', '伙', '但'], difficulty: 4 },
    { id: 456, character: '臆', hiddenWords: ['月', '立', '日', '口', '音', '意', '臆'], distractors: ['章', '竟', '韶', '意', '億', '薏', '骨', '胃', '背', '腎', '育', '肴'], difficulty: 4 },
    { id: 457, character: '薏', hiddenWords: ['草', '立', '日', '口', '音', '意', '薏'], distractors: ['章', '竟', '韶', '意', '億', '臆', '花', '菜', '蘆', '蘇', '蘢', '藺'], difficulty: 4 },
    { id: 458, character: '韶', hiddenWords: ['立', '日', '口', '音', '刀', '召', '韶'], distractors: ['章', '意', '竟', '招', '昭', '沼', '迢', '韶', '韶', '韶', '韶', '韶'], difficulty: 4 },
    { id: 459, character: '竟', hiddenWords: ['立', '日', '口', '儿', '竟'], distractors: ['音', '章', '意', '境', '鏡', '競', '兄', '克', '充', '兌', '吊', '竟'], difficulty: 3 },
    { id: 460, character: '境', hiddenWords: ['土', '立', '日', '口', '儿', '竟', '境'], distractors: ['音', '章', '意', '竟', '鏡', '競', '堂', '坐', '聖', '墨', '墾', '墊'], difficulty: 4 },
    { id: 461, character: '鏡', hiddenWords: ['金', '立', '日', '口', '儿', '竟', '鏡'], distractors: ['音', '章', '意', '竟', '境', '競', '鑑', '釜', '鑿', '鐵', '鋼', '銅'], difficulty: 4 },
    { id: 462, character: '競', hiddenWords: ['立', '口', '儿', '兄', '競'], distractors: ['音', '章', '意', '竟', '境', '鏡', '兢', '克', '充', '兌', '吊', '競'], difficulty: 4 },
    { id: 463, character: '兢', hiddenWords: ['十', '口', '儿', '克', '兢'], distractors: ['音', '章', '意', '竟', '境', '鏡', '競', '兄', '充', '兌', '吊', '兢'], difficulty: 4 },
    { id: 464, character: '克', hiddenWords: ['十', '口', '儿', '克'], distractors: ['兄', '兢', '充', '兌', '吊', '兢', '兢', '兢', '兢', '兢', '兢', '兢'], difficulty: 3 },
    { id: 465, character: '充', hiddenWords: ['儿', '充'], distractors: ['兄', '克', '兢', '兌', '吊', '允', '育', '流', '疏', '棄', '袞', '兗'], difficulty: 3 },
    { id: 466, character: '兌', hiddenWords: ['口', '儿', '兌'], distractors: ['兄', '克', '兢', '充', '吊', '說', '話', '語', '誰', '諸', '謝', '調'], difficulty: 3 },
    { id: 467, character: '吊', hiddenWords: ['口', '吊'], distractors: ['兄', '克', '兢', '充', '兌', '常', '賞', '掌', '裳', '躺', '棠', '糖'], difficulty: 3 },
    { id: 468, character: '常', hiddenWords: ['口', '巾', '常'], distractors: ['堂', '黨', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 3 },
    { id: 469, character: '賞', hiddenWords: ['口', '貝', '賞'], distractors: ['堂', '黨', '常', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 3 },
    { id: 470, character: '掌', hiddenWords: ['口', '手', '掌'], distractors: ['堂', '黨', '常', '賞', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 3 },
    { id: 471, character: '裳', hiddenWords: ['口', '衣', '裳'], distractors: ['堂', '黨', '常', '賞', '掌', '躺', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 4 },
    { id: 472, character: '躺', hiddenWords: ['身', '口', '躺'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '棠', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 4 },
    { id: 473, character: '棠', hiddenWords: ['口', '木', '人', '棠'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '螳', '鐺', '瞠', '糖', '膛'], difficulty: 4 },
    { id: 474, character: '糖', hiddenWords: ['米', '木', '人', '口', '糖'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '膛'], difficulty: 4 },
    { id: 475, character: '膛', hiddenWords: ['月', '口', '膛'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖'], difficulty: 4 },
    { id: 476, character: '螳', hiddenWords: ['虫', '口', '螳'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '鐺', '瞠', '糖', '膛'], difficulty: 4 },
    { id: 477, character: '鐺', hiddenWords: ['金', '口', '鐺'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '瞠', '糖', '膛'], difficulty: 4 },
    { id: 478, character: '瞠', hiddenWords: ['目', '口', '口', '瞠'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '糖', '膛'], difficulty: 4 },
    { id: 479, character: '糖', hiddenWords: ['米', '木', '人', '口', '糖'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '膛'], difficulty: 4 },
    { id: 480, character: '膛', hiddenWords: ['月', '口', '膛'], distractors: ['堂', '黨', '常', '賞', '掌', '裳', '躺', '棠', '螳', '鐺', '瞠', '糖'], difficulty: 4 },
    { id: 481, character: '最', hiddenWords: ['日', '口', '耳', '又', '取', '最'], distractors: ['曼', '冒', '冕', '勗', '聚', '趣', '娶', '職', '聰', '耿', '恥', '聊'], difficulty: 3 },
    { id: 482, character: '取', hiddenWords: ['耳', '又', '取'], distractors: ['最', '聚', '趣', '娶', '職', '聰', '耿', '恥', '聊', '聯', '聘', '耽'], difficulty: 3 },
    { id: 483, character: '聚', hiddenWords: ['耳', '又', '聚'], distractors: ['最', '取', '趣', '娶', '職', '聰', '驟', '驟', '叢', '眾', '從', '人'], difficulty: 4 },
    { id: 484, character: '趣', hiddenWords: ['土', '走', '耳', '又', '取', '趣'], distractors: ['最', '取', '聚', '娶', '職', '趨', '趙', '赶', '超', '越', '起', '徒'], difficulty: 4 },
    { id: 485, character: '娶', hiddenWords: ['耳', '又', '取', '女', '娶'], distractors: ['最', '取', '聚', '趣', '姿', '妥', '姜', '委', '婁', '娛', '姻', '媒'], difficulty: 4 },
    { id: 486, character: '罷', hiddenWords: ['四', '去', '土', '罷'], distractors: ['擺', '擺', '擺', '羆', '羆', '疲', '披', '被', '破', '波', '玻', '坡'], difficulty: 4 },
    { id: 487, character: '擺', hiddenWords: ['手', '四', '去', '土', '罷', '擺'], distractors: ['罷', '羆', '疲', '披', '被', '破', '波', '推', '拉', '提', '搬', '擦'], difficulty: 4 },
    { id: 488, character: '羆', hiddenWords: ['四', '去', '土', '火', '罷', '羆'], distractors: ['罷', '擺', '熊', '熙', '熟', '熱', '羔', '熬', '蒸', '烹', '煎', '烈'], difficulty: 4 },
    { id: 489, character: '熊', hiddenWords: ['匕', '月', '火', '熊'], distractors: ['羆', '熙', '熟', '熱', '羔', '熬', '蒸', '烹', '煎', '烈', '能', '態'], difficulty: 4 },
    { id: 490, character: '能', hiddenWords: ['匕', '月', '能'], distractors: ['熊', '態', '罷', '擺', '罷', '罷', '罷', '罷', '罷', '罷', '罷', '罷'], difficulty: 3 },
    { id: 491, character: '態', hiddenWords: ['匕', '月', '心', '能', '態'], distractors: ['熊', '能', '態', '怒', '怨', '愁', '憨', '憩', '憊', '懣', '憑', '懇'], difficulty: 4 },
    { id: 492, character: '憊', hiddenWords: ['广', '用', '心', '憊'], distractors: ['態', '能', '熊', '怒', '怨', '愁', '憨', '憩', '懣', '憑', '懇', '懸'], difficulty: 4 },
    { id: 493, character: '憑', hiddenWords: ['几', '馬', '心', '憑'], distractors: ['態', '能', '熊', '怒', '怨', '愁', '憨', '憩', '憊', '懣', '懇', '懸'], difficulty: 4 },
    { id: 494, character: '懇', hiddenWords: ['口', '疋', '心', '懇'], distractors: ['態', '能', '熊', '怒', '怨', '愁', '憨', '憩', '憊', '懣', '憑', '懸'], difficulty: 4 },
    { id: 495, character: '懸', hiddenWords: ['县', '目', '口', '心', '懸'], distractors: ['態', '能', '熊', '怒', '怨', '愁', '憨', '憩', '憊', '懣', '憑', '懇'], difficulty: 4 },
    { id: 496, character: '碧', hiddenWords: ['王', '白', '石', '口', '碧'], distractors: ['岩', '研', '破', '瑞', '玻', '璃', '璨', '粕', '泉', '原', '斑', '玛'], difficulty: 3 },
    { id: 497, character: '驾', hiddenWords: ['加', '力', '口', '马', '驾'], distractors: ['驾', '骂', '架', '枷', '茄', '驼', '驴', '驶', '驻', '驹', '骀', '驽'], difficulty: 3 },
    { id: 498, character: '骂', hiddenWords: ['口', '马', '骂'], distractors: ['驾', '架', '枷', '驼', '驴', '驶', '驻', '驹', '嚣', '哭', '器', '噪'], difficulty: 3 },
    { id: 499, character: '桑', hiddenWords: ['又', '木', '人', '桑'], distractors: ['集', '柔', '某', '架', '染', '条', '枭', '桒', '双', '叕', '圣', '仅'], difficulty: 3 },
    { id: 500, character: '染', hiddenWords: ['水', '九', '木', '人', '染'], distractors: ['桑', '柒', '梁', '柔', '某', '柴', '案', '剁', '杂', '烫', '浆', '桨'], difficulty: 3 }



];